### ISSUE TITLE
请问是否有计划在接下来的版本中移除某些库呢

### ISSUE THREAD

**Issue by qingmei2** [rosuH/AndroidFilePicker#1]
比如BRVAH,非必要的三方库是否会增加库 本身的体积？

**Comment by rosuH** [comment]
> 比如BRVAH,非必要的三方库是否会增加库 本身的体积？

前期也有考虑过这个问题。
体积会增加应该是肯定的。我会尽快量化出来。
也有可能会移除掉 BRVAH，改用原生方式实现。（虽然 BRVAH 用起来真的舒服~

**Comment by qingmei2** [comment]
唔，BRVAH在我看来太重了，绝大多数库的设计中下都不适合依赖并使用它，它使用起来很方便的原因也正是因为增加了在Adapter中增加了足够多的接口，这些接口意味着需要更多的依赖（比如SwipeRefreshLayout），这些成本本身是很隐蔽的，甚至是可能用不到的。

Google在涉及下拉刷新库的时候，没有基于Adapter出一个 SwipeRefreshAdapter，而是作为ViewGroup，我想也是这个原因，这种**基于现有功能的拓展，供用户选择性的添加**使得对列表刷新的实现方式更加灵活，而不是继承并拓展接口。

当然BRVAH本身这个库非常优秀，很多地方也很值得学习，我也只是简单提出自己的想法，如有冲撞请勿介意。我也很期待作者能设计出一个足够灵活的文件管理器，我会持续关注～ 😄

**Comment by qingmei2** [comment]
这个issue已经达到了个人的目的，作者看到就可以关了哈.

**Comment by rosuH** [comment]
细读了您的观点。受益匪浅。
想来确实有点偷懒了🤣，我会尽快使用原生方式实现的~
感谢您的关注和点评。

**Comment by rosuH** [comment]
@qingmei2 新的提交中以及移除了 BRVAH，感谢建议~
