### ISSUE TITLE
RecyclerView: No adapter attached; skipping layout

### ISSUE THREAD

**Issue by moonGosun** [rosuH/AndroidFilePicker#10]
在调试的时候发现console会出RecyclerView: No adapter attached; skipping layout这个错误

**Comment by rosuH** [comment]
@moonGosun 我大概了解了问题出现在哪了。这个问题不会对正常使用有什么影响。

### 问题原因
#### 直接原因
`RecyclerView` 被创建的时候没有设置 `Adapter` 的时候会抛出这个错误。

#### 分析
在 `FilePickerActivity.kt` 文件的[ `prepareLauncher()` ](https://github.com/rosuH/AndroidFilePicker/blob/0d697fbf893c2d317caa481cbaa527e85838c875/filepicker/src/main/java/me/rosuh/filepicker/FilePickerActivity.kt#L122)方法中，我用了协程来实现异步文件 I/O 然后更新 UI 的操作。（参看 #7 ）

注意两点：
1. `prepareLauncher()` 是在`onCreate()`中调用的

2. 

在该 `launch` 作用域最后调用了`initView()`这个方法：
```kotlin
private fun prepareLauncher() {
    // 执行顺序 ①
    launch {
        ...
    // 执行顺序 ③
        initView()
    }
    // 执行顺序 ②
}
```

所以最后的执行顺序会变成 
```
onCreate() --> prepareLauncher() --> onCreate() 结束 --> initView()

```

在 `onCreate()` 结束后没有为 `RecyclerView` 设置`Adapter`，所以提示了错误。

---
这是协程的黑魔法😄，我会考虑优化一下这个东西。
感谢提出建议~

**Comment by moonGosun** [comment]
good~
