### ISSUE TITLE
Android 11 MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by zivids** [rosuH/AndroidFilePicker#105]
请问可以考虑使用MANAGE_EXTERNAL_STORAGE兼容Android 11吗？
https://github.com/android/storage-samples

**Comment by rosuH** [comment]
这个权限我有关注。这个权限是给特殊场景（文件管理器/手机管家）之类使用的。
可能会导致审核变得严格。
https://support.google.com/googleplay/android-developer/answer/9956427?hl=zh-Hans#zippy=

不建议在 lib 层申请，这样会污染其他不想用此权限的用户。
你可以在你的项目申请这个权限，这样这个库应该是可以直接访问文件的。 不过我没测试过这个场景。

**Comment by zivids** [comment]
谢谢，我测试一下11下申请这个权限使用库访问文件

**Comment by zivids** [comment]
测试了一下，在11下会先跳转到系统的文件选择，后退就来到库的文件选择，但显示空白且提示未获取权限

**Comment by rosuH** [comment]
@zivids 已经支持 Android 11。可以尝试使用 0.7.4 版本。
