### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Kudychen7086** [rosuH/AndroidFilePicker#11]
doesn't work on Samsung SM-G9550 Android 8.0.0 API 26

**Comment by bingxuebage** [comment]
I/crash_recorder: getJavaCallStackImpl, @thread: 25191, 

       java.io.UnixFileSystem.list0(Native Method)
        java.io.UnixFileSystem.list(UnixFileSystem.java:303)
        java.io.File.list(File.java:1122)
        java.io.File.listFiles(File.java:1207)
        me.rosuh.filepicker.FilePickerActivity.isLotsOfFiles(FilePickerActivity.kt:400)
        me.rosuh.filepicker.FilePickerActivity.access$isLotsOfFiles(FilePickerActivity.kt:41)
        me.rosuh.filepicker.FilePickerActivity$prepareLauncher$1.invokeSuspend(FilePickerActivity.kt:131)
        kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)

**Comment by rosuH** [comment]
@Kudychen7086 Any other additional information?

**Comment by rosuH** [comment]
@bingxuebage There is less log information and it is not possible to determine the problem accurately.
But depending on the information you provide, it seems that the native level method is reporting an error. Is there a particularly large number of SD files?
Can you write a Demo and test it using the `File.listFiles()` method?

**Comment by bingxuebage** [comment]
@rosuH  是的native level出现的问题，是在我S8+手机上sdcard下有个大文件显示如下，我删也删不掉！
-rw-rw----  1 root sdcard_rw 225757852 2018-03-07 17:41 需求\爱?
如果真没有办法也就算了！

**Comment by rosuH** [comment]
@bingxuebage 你这文件应该是由 root 用户创建的？你试着用 root 权限删除掉。

**Comment by bingxuebage** [comment]
@rosuH  手机重置后没有这个问题了，谢谢你，麻烦了！

**Comment by Kudychen7086** [comment]
@rosuH  It seems cause by system unexpected spam files,thank you for your answer！

**Comment by rosuH** [comment]
@bingxuebage 上面那位是你的小号吗？😅

没想到你竟然重置了... 本来还觉得这个 bug 很有意思呢 😂
