### ISSUE TITLE
只能选择文件而不能选择文件夹，考虑增加下可以选择文件夹的功能吗

### ISSUE THREAD

**Issue by 7eu7d7** [rosuH/AndroidFilePicker#113]
只能选择文件而不能选择文件夹，考虑增加下可以选择文件夹的功能吗

**Comment by rosuH** [comment]
支持选择文件夹，请查看 Demo。

https://github.com/rosuH/AndroidFilePicker/blob/6b684e4c2fbf23fc49692f0a30aead019a69e2be/sample/src/main/java/me/rosuh/sample/SampleActivity.kt#L117-L140
