### ISSUE TITLE
localized OK button

### ISSUE THREAD

**Issue by loicteillard** [rosuH/AndroidFilePicker#12]
Please ! :)
![image](https://user-images.githubusercontent.com/198298/56193582-4479ae80-6031-11e9-920e-81f61f170bfc.png)

**Comment by rosuH** [comment]
@loicteillard I'm very sorry, this is my negligence. I will fix this later today, please wait a while.

**Comment by rosuH** [comment]
@loicteillard I had fix it in [0.4.3](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.4.3). 
Welcome to experience and provide advice.
Thank you~

**Comment by loicteillard** [comment]
Great, thanks !
