### ISSUE TITLE
怎样传递自己的参数，本来可以使用intent的，但是intent被内部封装了

### ISSUE THREAD

**Issue by liu-xinhui** [rosuH/AndroidFilePicker#126]

**Comment by rosuH** [comment]
@liu-xinhui 请问是什么样的场景或需求？

**Comment by liu-xinhui** [comment]
一个列表，每一条数据都有一个上传按钮，上传成功之后需要把文件url和这条数据对应的id，传递给后台。就是要传递这个id

**Comment by rosuH** [comment]
@liu-xinhui 那你现在应该只是拿这个库做文件选择对吧？我的理解是，你自己有一个列表的 UI 界面，而这个库只是帮你选择文件而已？

ID 不是存储在你自己的业务 UI 里吗？

**Comment by liu-xinhui** [comment]
因为一个onActivityResult会接收到多个文件，如果有了业务Id可以区分是哪个按钮选择的。如果不用intent传递，只能在点击选择文件按钮时保存当前id，也能实现，但是感觉不够优雅

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/119227554-15539680-bb41-11eb-8f5d-b0ee5a1a2dc2.png)
我已经用新的registerForActivityResult api实现传递参数了，多谢
