### ISSUE TITLE
启动直接xml报错

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [rosuH/AndroidFilePicker#13]
![image](https://user-images.githubusercontent.com/15881869/56559405-2cc39c80-65d4-11e9-8842-668a18dc2dbf.png)
如上图

**Comment by rosuH** [comment]
@AndroidJohnsonWang 你好，请问有其他辅助信息吗？
比如你的项目的版本、运行设备的版本等。

**Comment by erichyx** [comment]
好像是AndroidX项目出现的。

**Comment by AndroidJohnsonWang** [comment]
@rosuH android studio3.4，项目是androidx，compileSdkVersion 28 ，android4.4和9.0都出现问题，报错下面还有资源问题
![TIM图片20190424091314](https://user-images.githubusercontent.com/15881869/56625727-364f1200-6671-11e9-955d-ecd261c1596e.png)

**Comment by rosuH** [comment]
@AndroidJohnsonWang 我刚刚创建了一个新的 AndroidX 的项目，并没有出现一样的问题。
你是如何使用这个库的？直接在 `build.gradle` 添加依赖引入还是源码拷贝进项目的呢？

**Comment by AndroidJohnsonWang** [comment]
@rosuH 直接在 build.gradle 添加依赖引入的，我这边引入后出现超出方法数，用了multidex，不知道又没有影响

**Comment by AndroidJohnsonWang** [comment]
@rosuH 我也创建了一个新的 AndroidX 的项目，发现也是报错，但错误不是上面图片上的。怀疑是编译器版本问题，可以用android studio3.4试试？

**Comment by rosuH** [comment]
@AndroidJohnsonWang 我的也是 3.4。这个应该没什么影响吧。编译也是用 JDK 编译。
```
Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

这个问题还要继续确认，但是现在业余时间不是很够。可能会在五一假期的时候认真确认一下~

**Comment by rosuH** [comment]
@AndroidJohnsonWang 
我换了一个环境引入依旧是没有问题的。你可先把项目 clone 下来，运行里面的 Demo，看能否运行。
如果真是编译器的问题，那 Demo 应该是无法运行的。

**Comment by AndroidJohnsonWang** [comment]
@rosuH 测试发现demo 的minSDK 是21，用21以上设备使用正常，minSDK 改成19，无法编译通过了

**Comment by rosuH** [comment]
@AndroidJohnsonWang demo 更改 `minSDK` 报错的原因可能是 `sample` 模块内部命名和 `filepicker` 冲突了。应该和本主题一开始的事故无关。
我在 `dev` 分支解决了这个 Demo SDK 的问题。您可以继续尝试 clone 一下 demo 跑跑看。

本主题一开始的事故，个人觉得是`colorButtonNormal`这个属性的问题。不太确定，所以我也在`dev`更新了自定义样式部分内容。您有空可以引入 `dev` 版试试看？引入方法可以参看：https://github.com/rosuH/AndroidFilePicker/issues/15#issuecomment-493649285

期待您的反馈，谢谢~

**Comment by rosuH** [comment]
Android 4.4（API 19）的兼容性问题已经在 0.4.5 解决啦，欢迎使用后反馈。感谢~
