### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by HosseinKurd** [rosuH/AndroidFilePicker#132]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.FragmentTransaction android.app.FragmentManager.beginTransaction()' on a null object reference
        at android.app.DialogFragment.show(DialogFragment.java:238)
        at com.codekidlabs.storagechooser.StorageChooser.init(StorageChooser.java:107)
        at com.codekidlabs.storagechooser.StorageChooser.show(StorageChooser.java:67)

**Comment by rosuH** [comment]
@HosseinKurd Could you show me how did you use it? 😃

**Comment by HosseinKurd** [comment]
> @HosseinKurd Could you show me how did you use it? 😃
by Following the Readme file

**Comment by rosuH** [comment]
> > @HosseinKurd Could you show me how did you use it? 😃
> > by Following the Readme file

Can't reproduce...Any quick sample can be provided?

**Comment by rosuH** [comment]
Any new progress can be provided just reopen this issue and let me know.
