### ISSUE TITLE
AbstractFileFilter 过滤器问题 

### ISSUE THREAD

**Issue by KuiYang2017** [rosuH/AndroidFilePicker#133]
我用过滤器区分 图片 音频 视频之类的发现 过滤器 只能对当前当前目录的文件进行过滤 对于文件夹 并不能过滤其子文件

**Comment by rosuH** [comment]
是的。因为每次只会遍历当前文件夹。
不然就需要一直遍历到子文件夹，耗时将会很久。

**Comment by KuiYang2017** [comment]
使用自定义的方式 能否实现对整个文件的筛选

**Comment by rosuH** [comment]
> 使用自定义的方式 能否实现对整个文件的筛选

不行。每次都只会回调当前文件夹列表。底层的逻辑就是这样实现的。

**Comment by KuiYang2017** [comment]
好的 了解了
