### ISSUE TITLE
引入直接编译报错

### ISSUE THREAD

**Issue by KaelInvoker** [rosuH/AndroidFilePicker#15]
我的项目编译和目标版本是27，用gradle依赖下来，编译报错

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/57666895-3751de80-7634-11e9-9aff-60313fc8fa32.png)

**Comment by KaelInvoker** [comment]
试了下版本改成28就好了，不过这样还得适配28

**Comment by rosuH** [comment]
应该是库里面使用了 `kotlin-extentions`，所以强制需要 28 编译。这个很不友好，会改掉。

感谢~

**Comment by rosuH** [comment]
@KaelInvoker 嗨，我在 `dev` 分支移除了 `kotlin-extensions`，可能有助于你解决这个问题。
如果您有空的话，可以把 `dev` 分支引入项目看看，如果问题解决，我将在 `master` 发布。
引入 `dev` 分支方式：
```gradle
implementation 'me.rosuh:AndroidFilePicker:dev-SNAPSHOT'
```

期待您的反馈，感谢~

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/57998325-88197980-7b03-11e9-9147-37bf813296d2.png)
库依赖不成功

**Comment by rosuH** [comment]
@KaelInvoker 是这个：
```gradle
implementation 'me.rosuh:AndroidFilePicker:-SNAPSHOT'
```

**Comment by AndroidJohnsonWang** [comment]
> @KaelInvoker是这个：
> 
> ```groovy-gradle
> 实现' me.rosuh：AndroidFilePicker：-SNAPSHOT '
> ```

这个也不对
![image](https://user-images.githubusercontent.com/15881869/58016703-ef99ee00-7b30-11e9-9e17-247dac0429e4.png)

**Comment by rosuH** [comment]
@KaelInvoker @AndroidJohnsonWang 两位，昨天的库可能没有构建成功。
现在应该可以了：
```gradle
    implementation 'me.rosuh:AndroidFilePicker:dev-SNAPSHOT'

```

**Comment by DearYuzq** [comment]
我再更新到dev版本后，还是出现和上面两位一样的问题。

![image](https://user-images.githubusercontent.com/37435871/58067745-14d63d00-7bc1-11e9-95bc-d20dc7d71363.png)
![image](https://user-images.githubusercontent.com/37435871/58067751-1b64b480-7bc1-11e9-8ba0-6e270d4418e2.png)
![image](https://user-images.githubusercontent.com/37435871/58067758-23bcef80-7bc1-11e9-9a72-86095ad6159c.png)

**Comment by DearYuzq** [comment]
提示缺少文件，当我把这个文件创建后，可以正常使用
![image](https://user-images.githubusercontent.com/37435871/58067894-c07f8d00-7bc1-11e9-98b4-0142114d9611.png)

**Comment by rosuH** [comment]
@DearYuzq 请问你在项目的依赖中，找得到该文件吗？

![image](https://user-images.githubusercontent.com/15865017/58068201-fffaa900-7bc2-11e9-9aea-5646b7c516a9.png)

**Comment by DearYuzq** [comment]
@rosuH   是可以看到的，当SDK版本低于20时，这个文件好像不能生效

![image](https://user-images.githubusercontent.com/37435871/58068255-3f28fa00-7bc3-11e9-861b-e2448cbf09a8.png)

**Comment by rosuH** [comment]
@DearYuzq 我刚刚新建了一个项目，`minSdkVersion = 19`，`targetSdkVersion = 28` 没有出现类似情况呀 😿。试一下 `rebuild` 项目？

**Comment by rosuH** [comment]
@KaelInvoker @DearYuzq @AndroidJohnsonWang 请问大家，问题解决了吗？如果解决了我将合并到`master`分支。感谢反馈~

**Comment by rosuH** [comment]
我已经将`dev`合并到`master`了，大家可以尝试新版`0.4.4`。欢迎继续反馈。

**Comment by sazn1314** [comment]
@rosuH 你好,0.4.4依旧遇到这个问题,我目前安卓版本是4.4.3,高版本上没有问题

**Comment by rosuH** [comment]
@sazn1314 收到

**Comment by rosuH** [comment]
@sazn1314 Android 4.4（API 19）的兼容性问题已经在 [0.4.5](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.4.5) 解决啦，欢迎使用后反馈。感谢~
