### ISSUE TITLE
How to show PDF files?

### ISSUE THREAD

**Issue by amanzan** [rosuH/AndroidFilePicker#152]
I have PDF files downloaded in my device, but AndroidFilePicker does not show them, so I cannot select them. How can I do this?

**Comment by rosuH** [comment]
The above code is all your codes in the project? If not, just post all of them.

**Comment by mouness2020** [comment]
yes it's all code, and tested in these configs 
compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 30

Phone: Redmi note 9- android 11

**Comment by rosuH** [comment]
@Toprakete Do not recommend Using  `MANAGE_EXTERNAL_STORAGE` permission. Google Play would conduct special review.

**Comment by Toprakete** [comment]
@rosuH Yes, but that's ok, nothing to hide. As in https://developer.android.com/training/data-storage/manage-all-files to read, for 'On-device file search' it's ok to use this, I think
