### ISSUE TITLE
请问支持USB外接设备文件的选择么？

### ISSUE THREAD

**Issue by wragony** [rosuH/AndroidFilePicker#16]

**Comment by rosuH** [comment]
@wragony 当前版本不支持。不过从我个人角度来看，这个特性应该是必须支持的。
只是我个人对 USB/OTG 方面了解有限，而且该功能也需要兼容性测试，所以会逐步尝试支持但是可能没有那么快。
如果您对此比较熟悉，欢迎交流 PR~

**Comment by wragony** [comment]
期待！！！
