### ISSUE TITLE
可以支持一下文件排序吗

### ISSUE THREAD

**Issue by qq1642787610** [rosuH/AndroidFilePicker#17]
现在好像是默认到根目录 文件比较多 文件夹很散乱 没有顺序
找个文件都特别不好找

**Comment by rosuH** [comment]
收到，之前已经有人提交了 pr，只是因为在改 issue，所以没有合并。
会在最近时间合到 dev 的，感谢~

**Comment by rosuH** [comment]
@qq1642787610 已经添加在`dev`分支 https://github.com/rosuH/AndroidFilePicker/commit/88154483158d741409bb7394ff840bbd1a4ec9d2 。

因为`dev`修复了其它的部分问题，所以可能需要那些问题确认之后才会合并到主分支。大概这一两周。
不过您可以直接引入`dev`版：
```gradle
 implementation 'me.rosuh:AndroidFilePicker:dev-SNAPSHOT'
```

**Comment by KaelInvoker** [comment]
您好，这个文件排序现在支持么？
