### ISSUE TITLE
请问为什么pdf txt等文件无法显示？

### ISSUE THREAD

**Issue by OarUyGnah** [rosuH/AndroidFilePicker#172]
作者您好，我想问一下为什么只有图片和视频类型的可以显示，而pdf txt等类型的文件都无法显示呢，我使用了AbstractFileFilter
```
if (fileItemBean.isDir() 
    || fileItemBean.getFileType() instanceof TextFileType
    || fileItemBean.getFileType() instanceof PageLayoutFileType){
                        
    fileItemBeans.add(fileItemBean);
}
```
但仍然不能显示相关的类型文件，即使不使用AbstractFileFilter也是一样的，请问这是为什么呢，希望您能解答

**Comment by rosuH** [comment]
看下是不是这个情况：https://github.com/rosuH/AndroidFilePicker/issues/146#issuecomment-1038065959

**Comment by OarUyGnah** [comment]
好的，问题解决了，谢谢您
