### ISSUE TITLE
发布的版本打包kotlin插件版本号能否弄低一点？

### ISSUE THREAD

**Issue by MrDon94** [rosuH/AndroidFilePicker#177]
版本号过高又不兼容低版本的kotlin提示some kotlin libraries attached to this project were compiled with a newer Kotlin，
大佬你这个库0.8.0版本使用的kotlin插件是1.6.0，导致无法正常解析kotlin代码，编译倒是能运行，因为新版本的Android studio问题太多了，所以我改成稳定版本的Android Studio4.1.3版本，但是这个版本的kotlin插件最高只支持1.4.32

**Comment by rosuH** [comment]
😂这个需求有点奇怪。不影响运行的话，其实没啥比较调整。
如果你想看源码，来仓库看也行。或者你直接 clone 到本地，自己编译一份出来也可以
