### ISSUE TITLE
请问下这个是什么意思，

### ISSUE THREAD

**Issue by yexiang1994** [rosuH/AndroidFilePicker#18]
![1559563026(1)](https://user-images.githubusercontent.com/26133564/58800186-c94c7600-8639-11e9-914a-226e50aebe44.jpg)

**Comment by rosuH** [comment]
@yexiang1994 麻烦提供一下编译信息。参看 https://github.com/rosuH/AndroidFilePicker/issues/13

接着您可以使用 `dev` 版本，看看问题是否解决。

```
implementation 'me.rosuh:AndroidFilePicker:dev-SNAPSHOT'
```
