### ISSUE TITLE
为什么没有FilePickerManager类

### ISSUE THREAD

**Issue by sfy666666** [rosuH/AndroidFilePicker#183]
导不了包，不提示

**Comment by rosuH** [comment]
> 导不了包，不提示

sync 成功了吗？

**Comment by slowguy** [comment]
@sfy666666  你应该是漏掉了 maven { url 'https://jitpack.io' }

**Comment by Mystuddent** [comment]
我也遇到相同的问题了，sync 成功，但是没有FilePickerManager这个类。是因为哪里没有配置好么？
![image](https://user-images.githubusercontent.com/24928560/174569900-969cb83e-f0bb-4ac4-abc3-36c95427587c.png)

**Comment by rosuH** [comment]
> 我也遇到相同的问题了，sync 成功，但是没有FilePickerManager这个类，BuildConfig是java 类引入没问题。是因为哪里没有配置好么？
> 
> ![image](https://user-images.githubusercontent.com/24928560/174569900-969cb83e-f0bb-4ac4-abc3-36c95427587c.png)
> 
> 

看下 libraries 里面有没有这个库

**Comment by Mystuddent** [comment]
> > 我也遇到了同样的问题了，同步成功了，但是没有FilePickerManager这个类，BuildConfig是java类引入没问题。是因为哪里没有配置好么？
> > ![图片](https://user-images.githubusercontent.com/24928560/174569900-969cb83e-f0bb-4ac4-abc3-36c95427587c.png)
> 
> 看下库里面有没有这个库

你好，非常感谢作者，这么快就有回复。这个是我在gradle输出了依赖树，看到有引入的库。
![image](https://user-images.githubusercontent.com/24928560/174575427-8b51f443-cc6e-41b1-abbb-1f1fff57bfb6.png)

**Comment by Mystuddent** [comment]
不用查了，我使用新版本2021.2.1android studio打开项目就没有问题。电脑上有两个版本。
![image](https://user-images.githubusercontent.com/24928560/174577016-5ff8d073-6284-458e-b56d-cfdf95a955b4.png)
4.1.3版本不能通过
![image](https://user-images.githubusercontent.com/24928560/174577113-e1db6c54-c66d-43c8-b8f6-f16d52fe5383.png)

**Comment by rosuH** [comment]
> 不用查了，我使用新版本2021.2.1android studio打开项目就没有问题。电脑上有两个版本。
> 
> ![image](https://user-images.githubusercontent.com/24928560/174577016-5ff8d073-6284-458e-b56d-cfdf95a955b4.png)
> 
> 4.1.3版本不能通过
> 
> ![image](https://user-images.githubusercontent.com/24928560/174577113-e1db6c54-c66d-43c8-b8f6-f16d52fe5383.png)
> 
> 

那看起来像是 as 的问题，可以考虑 clean 然后 rebuild 试试看？

**Comment by Mystuddent** [comment]
> > 不用查了，我使用新版本2021.2.1android studio打开项目就没有问题。电脑上有两个版本。
> > ![image](https://user-images.githubusercontent.com/24928560/174577016-5ff8d073-6284-458e-b56d-cfdf95a955b4.png)
> > 4.1.3版本不能通过
> > ![image](https://user-images.githubusercontent.com/24928560/174577113-e1db6c54-c66d-43c8-b8f6-f16d52fe5383.png)
> 
> 那看起来像是 as 的问题，可以考虑 clean 然后 rebuild 试试看？

4.1.3之前我试过，不行。clean后重新rebuild没有用还是会找不到类

**Comment by rosuH** [comment]
> > > 不用查了，我使用新版本2021.2.1android studio打开项目就没有问题。电脑上有两个版本。
> 
> > > ![image](https://user-images.githubusercontent.com/24928560/174577016-5ff8d073-6284-458e-b56d-cfdf95a955b4.png)
> 
> > > 4.1.3版本不能通过
> 
> > > ![image](https://user-images.githubusercontent.com/24928560/174577113-e1db6c54-c66d-43c8-b8f6-f16d52fe5383.png)
> 
> > 
> 
> > 那看起来像是 as 的问题，可以考虑 clean 然后 rebuild 试试看？
> 
> 
> 
> 4.1.3之前我试过，不行。clean后重新rebuild没有用还是会找不到类

会不会可能是 as 的 kotlin 插件版本问题？

**Comment by rosuH** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/15865017/174626455-96477a66-de68-4f16-86d4-e042f63f083e.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/15865017/174626820-3e62359d-0acc-406d-a85a-23000eca51d4.png">


我刚刚开了个新项目，应该是没问题的。

**Comment by sfy666666** [comment]
感谢作者回复，已经解决了
