### ISSUE TITLE
文件排序现在支持了么？

### ISSUE THREAD

**Issue by KaelInvoker** [rosuH/AndroidFilePicker#19]
如题，文件排序现在支持了么？

**Comment by rosuH** [comment]
@KaelInvoker 已经支持啦，会根据文件名字母序进行排序。

https://github.com/rosuH/AndroidFilePicker/commit/88154483158d741409bb7394ff840bbd1a4ec9d2#diff-e06a5876a6289544cd4e02f101cb8b1eR60

**Comment by KaelInvoker** [comment]
感谢大佬

**Comment by KaelInvoker** [comment]
请问，引入需要配置混淆么？
