### ISSUE TITLE
单选

### ISSUE THREAD

**Issue by limuyang2** [rosuH/AndroidFilePicker#2]
是否可以实现单选？

**Comment by rosuH** [comment]
@limuyang2 这个周末我着手开始加上哈~

**Comment by rosuH** [comment]
@limuyang2 嗨，单选功能已经加上咯，欢迎测试使用哈

https://github.com/rosuH/AndroidFilePicker/commit/095b710498a560ba8f995f051847bb6555aeeb77

**Comment by Aniderr** [comment]
> @limuyang2 嗨，单选功能已经加上咯，欢迎测试使用哈
> 
> [095b710](https://github.com/rosuH/AndroidFilePicker/commit/095b710498a560ba8f995f051847bb6555aeeb77)

请问一下 单选应该如何配置啊？我看文档没有说明~谢谢
