### ISSUE TITLE
返回键的优化性建议

### ISSUE THREAD

**Issue by KaelInvoker** [rosuH/AndroidFilePicker#21]
现在每次打开下一级目录，再返回上一级目录时，没有记录上次滑动的位置，导致体验上很差。

**Comment by rosuH** [comment]
@KaelInvoker 滑动位置记录已经添加了 [0.4.8](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.4.8)

欢迎使用并反馈，感谢~

**Comment by KaelInvoker** [comment]
试过了，ok了
