### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by prettygirl20231** [rosuH/AndroidFilePicker#213]
我adb命令将文件push到了sdcard,使用adb shell也能看到；但是文件选择器找不到这个文件；甚至模拟器自带的文件管理器也找不到这个文件

**Comment by rosuH** [comment]
看下是不是文件名编码有问题？pull 到你的电脑，重新改下名字再push进去看看

**Comment by prettygirl20231** [comment]
> 看下是不是文件名编码有问题？pull 到你的电脑，重新改下名字再push进去看看

我发现push 到sdcard/Docments目录时，并没有进入这个目录(adb shell显示该目录下有，模拟器的文件管理器找不到)，而是经入了一个sdk_gphone64_x86_64/Documents目录下了，这是什么原因呢

**Comment by rosuH** [comment]
> > 看下是不是文件名编码有问题？pull 到你的电脑，重新改下名字再push进去看看
> 
> 
> 
> 我发现push 到sdcard/Docments目录时，并没有进入这个目录(adb shell显示该目录下有，模拟器的文件管理器找不到)，而是经入了一个sdk_gphone64_x86_64/Documents目录下了，这是什么原因呢

不太清楚这个问题，可以用真实设备试试看
