### ISSUE TITLE
我这边好像不显示内容

### ISSUE THREAD

**Issue by badboy-tian** [rosuH/AndroidFilePicker#221]
```
FilePickerManager.from(this@NewMainActivity).filter(audioFilter).forResult(10086)

    public val audioFilter = object : AbstractFileFilter() {
            override fun doFilter(listData: ArrayList<FileItemBeanImpl>): ArrayList<FileItemBeanImpl> {
                return ArrayList(listData.filter { item ->
                    ((item.isDir) || (item.filePath.endsWith(".mp3")
                            || item.filePath.endsWith(".m4a")
                            || item.filePath.endsWith(".aac")
                            || item.filePath.endsWith(".wav")
                            ))
                })
            }
        }

compileSdkVersion 33
targetSdkVersion 33
```
小米手机 miui 14.0.7  android 13
小米自带的文件管理可以看到
<img width="726" alt="image" src="https://github.com/rosuH/AndroidFilePicker/assets/2835129/97953b6a-7cde-4863-ab9f-9134d60958cc">
也给了权限:
<img width="682" alt="image" src="https://github.com/rosuH/AndroidFilePicker/assets/2835129/398b92a6-6d40-4b8f-89df-d7cc40feebab">
但是在app里面打开不行, 没有内容
<img width="541" alt="image" src="https://github.com/rosuH/AndroidFilePicker/assets/2835129/f3125b49-5df8-496f-a86b-96c9851d449b">

日志里面也没有报错

**Comment by badboy-tian** [comment]
刚刚看了下 是MIUI/sound_recorder/app_rec这个目录不行  我把文件复制到sdcard根目录 可以正常读取 不知道这个目录需要特殊权限?

**Comment by badboy-tian** [comment]
搜了下无解...

**Comment by rosuH** [comment]
> 刚刚看了下 是MIUI/sound_recorder/app_rec这个目录不行  我把文件复制到sdcard根目录 可以正常读取 不知道这个目录需要特殊权限?

应该是权限问题，看命名是通话录音还是系统的录音 App 的目录？
target 33 只能展示你的 App 有权限访问的文件。

https://github.com/rosuH/AndroidFilePicker/blob/master/README_CN.md#%E7%89%88%E6%9C%AC%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by badboy-tian** [comment]
不知道小米搞什么飞机了....MIUI/sound_recorder 这个目录里面有通话录音目录, 系统录音APP的录音文件目录  很奇葩  按道理也不应该要什么权限 搞不懂 算了 不管了  复制到其他目录是可以显示的
