### ISSUE TITLE
设置默认打开目录

### ISSUE THREAD

**Issue by taosimple** [rosuH/AndroidFilePicker#24]
好像没有设置默认打开目录的功能，希望能加上

**Comment by rosuH** [comment]
收到～

**Comment by rosuH** [comment]
自定义起始位置的功能已经在 v0.5.0 加上了，使用请参考[更多示例](https://github.com/rosuH/AndroidFilePicker/wiki/4.-%E7%A4%BA%E4%BE%8B%E5%8F%8A%E8%A7%A3%E9%87%8A)
