### ISSUE TITLE
文字显示有异常

### ISSUE THREAD

**Issue by EmKs** [rosuH/AndroidFilePicker#25]
系统为中文的情况下，默认显示为英文，此时自定义文字内容，将文字改为中文，初次打开依旧为英文（初次打开自定义文字没生效，需要选中或打开打开下一级的文件夹文字才会更新）

**Comment by rosuH** [comment]
@EmKs 麻烦提高更多的信息，比如 ROM 、系统语言设置之类。因为项目里使用的是`strings.xml`文件，会自动根据系统设置切换的。是不是设置了繁体或者地区为 HK 或 台湾？

**Comment by EmKs** [comment]
@rosuH 发现问题了，抱歉，是我这边配置了打包过滤的问题。不过那个自定义文字的Bug还是存在，用的是As自带的模拟器，比如我自定义“全选”的文字为test，但是初次打开时还是显示全选，需要进入下一级文件夹刷新文件目录后“全选”才会变成test

**Comment by EmKs** [comment]
@rosuH 另外后面会不会考虑加上动画，目前切换目录的时候没有动画感觉有些生硬

**Comment by rosuH** [comment]
> @rosuH 另外后面会不会考虑加上动画，目前切换目录的时候没有动画感觉有些生硬

在 feature 分支上已经加入动画了，会在下个版本合并进去哈~感谢建议 😃

**Comment by rosuH** [comment]
嗨，自定义文字失效问题应该已经在 [0.4.7](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.4.7) 上解决了。
同时增加了加载动画、下拉刷新和空视图，欢迎使用并反馈，感谢~
