### ISSUE TITLE
文件夹列表点击文件夹图标点击无效,要点击除文件夹图标外的地方.

### ISSUE THREAD

**Issue by YumikoAzu** [rosuH/AndroidFilePicker#27]

**Comment by rosuH** [comment]
因为在 item 中，选择图标是可以直接选中的。没有对文件夹做处理，所以点击无效。感谢反馈～

**Comment by rosuH** [comment]
Fix in https://github.com/rosuH/AndroidFilePicker/commit/38a43b8700113b4c56c634c683cca7ba33f431d5 .
