### ISSUE TITLE
我在使用中获取音频文件和图片文件时显示没有文件，获取视频文件时可以正常显示

### ISSUE THREAD

**Issue by NiuXiaoGuang** [rosuH/AndroidFilePicker#30]

**Comment by rosuH** [comment]
应该是文件后缀没有识别出来吧。我看到您已经 fork 并添加了 `flac` 后缀的格式。欢迎 PR ～

**Comment by rosuH** [comment]
不过无法在项目内涵盖所有的文件类型，所以建议是自定义自己的文件类。
我会把文件类型、文件甄别器的使用做一个 Demo 出来。

**Comment by NiuXiaoGuang** [comment]
我在使用的时候过滤器设置为AudioFileType 类型的，显示没有内容，但实际上我的手机里面有很多歌曲，包括（.MP3，.flac，.wav）  我也想自定义文件类，可是Kotlin语言开不太明白。。。

**Comment by NiuXiaoGuang** [comment]
> 不过无法在项目内涵盖所有的文件类型，所以建议是自定义自己的文件类。
> 我会把文件类型，文件甄别器的使用做一个Demo出来。


你在手机上能够获取音频文件和图片文件么，

**Comment by rosuH** [comment]
@NiuXiaoGuang 可以的。但是 flac 后缀库里没有支持。周末更新一下～
