### ISSUE TITLE
kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by KaelInvoker** [rosuH/AndroidFilePicker#31]
bugly上报崩溃
![image](https://user-images.githubusercontent.com/37531571/61443482-2eef8a00-a97c-11e9-81a8-52b3574276ca.png)

**Comment by rosuH** [comment]
@KaelInvoker 能贴一下是怎么调用这个库的吗？照道理应该不会出现这个错误。

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/61457600-3ffbc380-a99b-11e9-9cbd-ce2d702aab3e.png)

**Comment by rosuH** [comment]
奔溃率高吗？

**Comment by KaelInvoker** [comment]
目前只发生了2次

**Comment by rosuH** [comment]
代码应该没有什么问题...使用的是 Kotlin 的延迟初始化。除非 JVM 对代码执行顺序做了重排序...
希望能提供一下更多信息，比如库版本、奔溃机型的详细信息，比较好定位。
感谢~

**Comment by rosuH** [comment]
尝试在 [0.4.9](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.4.9) 修复了这个问题。但是无法十分确定原因。如果后续仍有问题，欢迎重开 issues

**Comment by KaelInvoker** [comment]
好的，大佬

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/61767963-7bbddf80-ae18-11e9-98f1-fb6e851cc070.png)
![image](https://user-images.githubusercontent.com/37531571/61768049-cf302d80-ae18-11e9-9064-49cec0e455bd.png)

**Comment by KaelInvoker** [comment]
使用的版本是0.4.6

**Comment by rosuH** [comment]
在 v0.5.0 版本上删除了延迟初始化的代码，应该不会有类似问题出现了。如果有问题欢迎随时反馈。

**Comment by rosuH** [comment]
@KaelInvoker 你好，请问当时是否是在 Fragment 中使用的呢？
