### ISSUE TITLE
希望直接扫描出所有指定类型的文件

### ISSUE THREAD

**Issue by NiuXiaoGuang** [rosuH/AndroidFilePicker#32]

**Comment by rosuH** [comment]
不是的。子目录肯定也是支持的。
建议提供一下调用方式和文件列表，比较容易排查问题~

**Comment by NiuXiaoGuang** [comment]
> 不是的。子目录肯定也是支持的。
> 建议提供一下调用方式和文件列表，比较容易排查问题〜

![image](https://user-images.githubusercontent.com/30843465/61573856-1dc38c00-aae8-11e9-9551-99e928d581f0.png)
![image](https://user-images.githubusercontent.com/30843465/61573857-24ea9a00-aae8-11e9-8f01-0cfe01ca332f.png)


![U34}0EZ@@3J3`XYT4U}DV8O](https://user-images.githubusercontent.com/30843465/61573886-afcb9480-aae8-11e9-9f21-c3a26ff9c22d.jpg)

![$4 4B%4B$BL%VLVFS07R%6C](https://user-images.githubusercontent.com/30843465/61573892-b8bc6600-aae8-11e9-8120-47b73f6fd96c.jpg)

**Comment by rosuH** [comment]
@NiuXiaoGuang 调用方式有问题...你把文件夹过滤了呀...

正确的应该还要加上`isDir`判断。然后也不需要加上`isChecked()`，因为这个列表是最终的显示列表，还没有被选中的。

```java
...
if (fileItemBean.isDir || fileItemBean.getFileType() instanceof AudioFileType){
    fileItemBeans.add(fileItemBean)
}

```

**Comment by NiuXiaoGuang** [comment]
> @NiuXiaoGuang调用方式有问题......你把文件夹过滤了呀......
> 
> 的正确应该还要加上`isDir`判断。然后也不需要加上`isChecked()`，因为这个列表是最终的显示列表，还没有被选中的。
> 
> ```java
> ...... 
> 如果（fileItemBean 。 ISDIR || fileItemBean 。 getFileType（）的instanceof  AudioFileType）{
>     fileItemBeans 。添加（fileItemBean）
> }
> ```

我按照你说的方式调用，但是结果还是不太理想，还是需要打开子文件夹才能找到，手机的文件夹太多了。能不能改进下，调用之后直接显示想要的指定文件类型而不包括文件夹，这样字比较直观一点

**Comment by rosuH** [comment]
你想要的效果应该是直接扫描出所有指定类型的文件。这个功能现在还没有，后面会考虑加上~

**Comment by NiuXiaoGuang** [comment]
> 你想要的效果应该是直接扫描出所有指定类型的文件。这个功能现在还没有，后面会考虑加上〜

拭目以待

**Comment by rosuH** [comment]
@NiuXiaoGuang 您好，如果想直接选中特定类型的文件。
推荐可以使用系统的 [SAF](https://developer.android.com/guide/topics/providers/document-provider#open-client) 进行访问。体验会更好。

**Comment by wayuhan** [comment]
0.6.0版本支持这个功能了吗

**Comment by rosuH** [comment]
@wayuhan 还没有支持。可以看上一条评论。
因为如果这个库要做这件事情的话，会有点麻烦。所以我的推荐是建议使用系统的 SAF 进行访问。

**Comment by wayuhan** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rosuH"<notifications@github.com&gt;; 
发送时间: 2020年1月8日(星期三) 上午9:49
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "陈鑫"<879530600@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] 希望直接扫描出所有指定类型的文件 (#32)




@wayuhan 还没有支持。可以看上一条评论。
 因为如果这个库要做这件事情的话，会有点麻烦。所以我的推荐是建议使用系统的 SAF 进行访问。
