### ISSUE TITLE
能否获取到content://格式的目录？

### ISSUE THREAD

**Issue by EmKs** [rosuH/AndroidFilePicker#33]
例如webview调用系统自带的文件选择器返回的结果是以content://格式的路径

**Comment by rosuH** [comment]
不太确定您的意思。您是想用此库来访问 ContentProvider 提供的 URI 链接吗？还是说要把返回的结果转换为 URI 形式?

**Comment by EmKs** [comment]
@rosuH 通过此库访问ContentProvider 提供的 URI，用于传递文件目录给webview，当前获取到的储存目录无法用于webview上传，目前我是使用Uri.parser(new File)去转换的

**Comment by rosuH** [comment]
@EmKs 您好，抱歉这么就才回复。有点疑问想和您讨论下：

> 通过此库访问 ContentProvider 提供的 URI，用于传递文件目录给webview

指的是从其他 APP 拿到了 ContentProvider 的链接 `content://example/file` 然后使用本库打开以浏览文件，接着选中文件后返回 `content://example/file/file1` 格式的链接。
是这样吗？
