### ISSUE TITLE
我在打算项目上线前进行云测试，结果报错

### ISSUE THREAD

**Issue by NiuXiaoGuang** [rosuH/AndroidFilePicker#34]
![image](https://user-images.githubusercontent.com/30843465/61705621-b4a67780-ad78-11e9-93d9-3d693ad74696.png)

**Comment by NiuXiaoGuang** [comment]
云测试平台是小米云测试

**Comment by rosuH** [comment]
麻烦提供更详细的信息，系统版本、库版本、出错堆栈等
