### ISSUE TITLE
选择存储位置问题

### ISSUE THREAD

**Issue by ChuHuiCyg** [rosuH/AndroidFilePicker#35]
我看了下FileUtils.kt 中
方法fun getRootFile():File
发现无论我设置说明存储类型他都说返回同一个位置的路径:
File(Environment.getExternalStorageDirectory().absoluteFile.toURI())

**Comment by rosuH** [comment]
是的，当前版本还不支持传入根目录路径。已经正在开发了~

**Comment by rosuH** [comment]
自定义起始位置的功能已经在 v0.5.0 加上了，使用请参考 [更多示例](https://github.com/rosuH/AndroidFilePicker/wiki/4.-%E7%A4%BA%E4%BE%8B%E5%8F%8A%E8%A7%A3%E9%87%8A)
