### ISSUE TITLE
单选的时候，顶部能不能不显示全选的按钮？

### ISSUE THREAD

**Issue by KaelInvoker** [rosuH/AndroidFilePicker#36]
如题。现在单选的时候，出现了全选，取消全选，选择框也是复选框，我们测试说会误导客户...大佬，这些能改成单选时，全选和取消全选去掉，选择框改为单选框么？

**Comment by KaelInvoker** [comment]
大佬，这个改好了么？

**Comment by rosuH** [comment]
@KaelInvoker 这个周末应该可以～

**Comment by rosuH** [comment]
Fix on [0.5.1](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.5.1)

**Comment by KaelInvoker** [comment]
大佬，调用enableSingleChoice()，只是隐藏了头部的全选和取消全选，但还是可以多选，必须指定选择数量，调用起来有点啰嗦。另外单选模式下，选择的按钮样式能从复选框变成单选框么?

**Comment by KaelInvoker** [comment]
大佬，这个什么时候能完成？

**Comment by rosuH** [comment]
@KaelInvoker 如果您业务紧急，还是建议直接 Fork 然后修改。我是业余时间维护，也有自己的工作。

**Comment by rosuH** [comment]
@KaelInvoker 
> 选择的按钮样式能从复选框变成单选框么

这个单选框具体的意思是啥？是说改成选中后再显示吗？🤔

**Comment by KaelInvoker** [comment]
大佬，意思是单选模式下，显示逻辑还是不变，只是选择框现在的样式改成单选框的样式：就是把框改成圆圈

**Comment by rosuH** [comment]
@KaelInvoker  您好，单选模式已经正式发布。
您可以使用最新的 `0.6.0` 体验。该版本对部分 API 亦有小改动，如果遇到问题也可以直接在本 issue 提出或新建一个新 issue 。

感谢反馈～
