### ISSUE TITLE
可否添加选择文件夹的功能？

### ISSUE THREAD

**Issue by DanteAndroid** [rosuH/AndroidFilePicker#4]
既然名字叫`FilePicker`，而实际上 Directory 也是 File，所以添加选择文件夹的功能也是很正常的吧？

以上都是胡扯，就是我需要这个功能（单选/多选文件夹）……

**Comment by rosuH** [comment]
@DanteAndroid 可以呀。目前已经可以多选文件夹了。单选功能正在做。

晚上我更新一下使用示例。:smile:

**Comment by DanteAndroid** [comment]
顺便问下啊，如果想筛选含有图片的文件夹应该怎么实现比较好？

**Comment by rosuH** [comment]
@DanteAndroid 嗨，文件夹选择功能已经完善好咯，可以看看  [wiki](https://github.com/rosuH/AndroidFilePicker/wiki/4.-%E7%A4%BA%E4%BE%8B%E5%8F%8A%E8%A7%A3%E9%87%8A) 里的示例，也可以把项目`clone`下来跑一下哈。

-----
> 顺便问下啊，如果想筛选含有图片的文件夹应该怎么实现比较好？

这个可能比较难实现。因为你这个需要一开始就对整个目录进行完全遍历。
而我这里只会遍历一级子目录，不会完全遍历。emmm...要么你`fork`过去魔改一下....或者...等看看我什么时候把框架里的浏览和路径解耦出来（大坑）😂

**Comment by rosuH** [comment]
此 issue 将被关闭，如果您还有问题欢迎继续讨论或重开~
