### ISSUE TITLE
能否指定默认打开目录，而非指定根目录

### ISSUE THREAD

**Issue by Orienser** [rosuH/AndroidFilePicker#41]
目前可用CustomRootPath指定打开时的根目录，但因为是根目录的关系，选择时无法返回上一级目录。
能否指定一个起始目录，我打开选择器后会进入该起始目录，如果起始目录非根目录时，还可以正常返回上一级目录。
这在实现有记忆上一次用户选择的路径的功能的文件选择器时很有用。

**Comment by MrZzhouWorld** [comment]
这个功能有完善嘛，大佬

**Comment by rosuH** [comment]
@MrZzhouWorld 抱歉哈，这个暂时还没有做。因为涉及到内部逻辑的调整。我这几天想想看看。下周末给您答复。

**Comment by rosuH** [comment]
@MrZzhouWorld 您好，我理了一下代码。发现可能改动会比较大。近期不会增加这个功能哈，抱歉～

**Comment by monakatyking** [comment]
请问什么时候能增加这个功能，目前自定义根目录后无法返回上一级，挺不方便的

**Comment by monakatyking** [comment]
> @MrZzhouWorld 您好，我理了一下代码。发现可能改动会比较大。近期不会增加这个功能哈，抱歉～

请问什么时候能增加这个功能，目前自定义根目录后无法返回上一级，挺不方便的

**Comment by rosuH** [comment]
已在 `0.7.5` 中支持，欢迎体验和反馈～
