### ISSUE TITLE
文件排序待优化

### ISSUE THREAD

**Issue by YumikoAzu** [rosuH/AndroidFilePicker#44]
![IMG_8189](https://user-images.githubusercontent.com/13196251/64515847-f470f080-d31f-11e9-8361-cb727b24f40f.JPG)
![IMG_8190](https://user-images.githubusercontent.com/13196251/64515865-fa66d180-d31f-11e9-947b-63adc2b7912e.JPG)

**Comment by rosuH** [comment]
麻烦附上使用代码 @YumikoAzu

**Comment by YumikoAzu** [comment]
@rosuH 就是你的DEMO。0.5.1版本的。图中两个自己创建的文件夹aa和aaa就没有显示出来.。。

**Comment by rosuH** [comment]
@YumikoAzu 是 demo 哪个方法？或是哪个按钮呢？

**Comment by YumikoAzu** [comment]
@rosuH  你的项目跑起来,里面所有按钮都显示不了自己创建的文件夹。

**Comment by rosuH** [comment]
请问显示不了的文件夹是如何创建的呢？系统的文件管理器或者其他文件管理器可以显示吗？ @YumikoAzu

**Comment by YumikoAzu** [comment]
@rosuH 其他文件管理器可以显示，第一张图的es文件管理器就行。那些文件夹我用es文件管理器创建的。。。

**Comment by rosuH** [comment]
@YumikoAzu 应该是有的。你创建的文件夹是小写字母开头，会在列表后面显示的...
我后续再优化一下排序规则。

**Comment by YumikoAzu** [comment]
@rosuH 刚刚看到了。。。

**Comment by YumikoAzu** [comment]
@rosuH 排序到后面去了

**Comment by rosuH** [comment]
您好，已经在提交 https://github.com/rosuH/AndroidFilePicker/commit/30002246a41813aa55be6cefc7d7889fc96c9389. 中修复。

会在下一版本发布此次更新，感谢反馈。
