### ISSUE TITLE
请问作者这个库适配Q了吗？

### ISSUE THREAD

**Issue by waws80** [rosuH/AndroidFilePicker#46]

**Comment by rosuH** [comment]
如果你的`targetSdkVersion < 28`，那么可以在 Q 上正常使用。
如果你的`targetSdkVersion >= 29`，那么还不能在 Q 上使用。
这几天会做好兼容，非常感谢。

**Comment by WhoJave** [comment]
android 10 会闪退有好的法子么

**Comment by rosuH** [comment]
@WhoJave 当前还没有兼容 Q。
你的 targetSdkVersion 设置为 29 了嘛？不然是不会崩溃的。

**Comment by WhoJave** [comment]
@rosuH 嗯 是设置targetSdkVersion 29的 用legacy storage可以了

**Comment by rosuH** [comment]
@WhoJave 是的，目前可以使用这个[策略](https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage)。

因为 Android 10 的存储权限变更，考虑到未来需求的不确定性，所以暂时不做兼容。
如果是一定要兼容最新的 Android 10 的存储内容，建议使用 SAF 进行文件获取。

- [访问文件所需权限](https://developer.android.com/training/data-storage/files/external-scoped#permissions-required)
- [存储访问框架](https://developer.android.com/guide/topics/providers/document-provider)
