### ISSUE TITLE
java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'

### ISSUE THREAD

**Issue by KuiYang2017** [rosuH/AndroidFilePicker#49]
java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' 
在调用的时候出现这个问题

**Comment by rosuH** [comment]
是在 demo 还是你自己的项目调用呢？

**Comment by KuiYang2017** [comment]
自己项目调用

**Comment by rosuH** [comment]
@KuiYang2017 有没有加混淆呢？

**Comment by KuiYang2017** [comment]
之前没有,出现这个问题 . 我寻求方法  找到一个解决方案
`# ServiceLoader support
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepnames class kotlinx.coroutines.android.AndroidExceptionPreHandler {}
-keepnames class kotlinx.coroutines.android.AndroidDispatcherFactory {}

# Most of volatile fields are updated with AFU and should not be mangled
-keepclassmembernames class kotlinx.** {
    volatile <fields>;`
但我的问题依然存在

**Comment by rosuH** [comment]
加了下面的混淆吗？
```
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepnames class kotlinx.coroutines.android.AndroidExceptionPreHandler {}
-keepnames class kotlinx.coroutines.android.AndroidDispatcherFactory {}

-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
```

**Comment by KuiYang2017** [comment]
是的 依然不行

**Comment by rosuH** [comment]
是 Debug 模式就不行了吗？还是 release 包

**Comment by KuiYang2017** [comment]
release包不行

**Comment by rosuH** [comment]
如果 release 包不行，那应该还是混淆的问题。我用 demo 打了 release 包，没有复现这个问题。

**Comment by KuiYang2017** [comment]
是这样的 之前是直接安装的 现在是集成到一个叫awork的软件安装的,直接安装的没有问题,集成的有问题

**Comment by KuiYang2017** [comment]
我单独打包 集成进awork 也是报错,报这个错误

**Comment by rosuH** [comment]
要确认一下：
1. 集成的和直接安装的都是 release 包是吗？还是说直接安装的是 debug 版？
2. aWork 是[深信服的 aWork高级版安装工具 ](https://bbs.sangfor.com.cn/forum.php?mod=forumdisplay&fid=49#/software/undefined/100000025367187/all) 吗？
3. 如果现在您直接安装，会不会报错？排除一下是不是 aWork 的影响。

**Comment by KuiYang2017** [comment]
1 都是
2 是
3 直接安装不会出错,,可以肯定是aWork的影响,
但是这个地方是程序出错了.我在想是不是aWork对app比较严格,直接把这个问题暴露出来了

**Comment by rosuH** [comment]
因为我这里无法测试 aWork 的安装。你可以试试新建一个项目，里面只引入这个库并调用一下。
然后打个 release 包，安装看看有没有问题。

或者用我刚打包出来的 demo 也可以：

[release.zip](https://github.com/rosuH/AndroidFilePicker/files/3669557/release.zip)

**Comment by KuiYang2017** [comment]
我把demo打了个release 集成到aWork里了,还是有这个问题.
这个文件选择器能不能提供一个纯java环境的.

**Comment by rosuH** [comment]
Demo 里没有加混淆的 😂...你把我打出来的那个装进去试试看？

此外，这个应该不是 Kotlin 的问题，可能是 aWork 的某些安全机制，对 [协程库](https://github.com/Kotlin/kotlinx.coroutines) 的混淆有所影响。

我可以使用原生的线程实现现在的功能，但是需要一到两天的时间重写一下。

**Comment by KuiYang2017** [comment]
其实本身的app其实也没加混淆🤣

**Comment by rosuH** [comment]
> 其实本身的app其实也没加混淆🤣

😮 你的 gradle 脚本里没有`minifyEnabled true`参数吗？

**Comment by KuiYang2017** [comment]
并没有  设置了false

**Comment by KuiYang2017** [comment]
你打的包 发给aWork封测人员,提示app可能已损坏

**Comment by rosuH** [comment]
> 你打的包 发给aWork封测人员,提示app可能已损坏

...我对此完全无法发表任何看法，无知限制了我的想象力...😂

**Comment by KuiYang2017** [comment]
![image](https://user-images.githubusercontent.com/9023491/65867031-55806700-e3a8-11e9-850a-656d1fa5fd37.png)
我们也不知道 为什么客户要用这个aWork

**Comment by rosuH** [comment]
> ![image](https://user-images.githubusercontent.com/9023491/65867031-55806700-e3a8-11e9-850a-656d1fa5fd37.png)
> 我们也不知道 为什么客户要用这个aWork

可能是限制系统和 APP 的功能。用于一些定制设备吧。

**Comment by rosuH** [comment]
已在 [0.5.2](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.5.2) 中修复。
