### ISSUE TITLE
请问有java版本吗

### ISSUE THREAD

**Issue by baohexin** [rosuH/AndroidFilePicker#5]

**Comment by rosuH** [comment]
@baohexin 指的是示例代码吗？我更新了[过滤器的 Java 版本](https://github.com/rosuH/AndroidFilePicker/wiki/2.-%E8%BF%87%E6%BB%A4%E5%99%A8%EF%BC%9A%E5%8F%AA%E6%98%BE%E7%A4%BA%E6%9F%90%E7%A7%8D%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%96%87%E4%BB%B6)，至于其他的使用...Kotlin 和 Java 基本一致的。

有疑问欢迎继续提出~

**Comment by limuyang2** [comment]
java使用基本无差异，可以同样使用

**Comment by rosuH** [comment]
嗨，此 issue 将被关闭，如果您还有问题欢迎继续讨论或重开~

**Comment by qinyang1018** [comment]
建议在readme上增加下java的调用
````
 mSelectBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                FilePickerManager.INSTANCE
                        .from(SelectVideoActivity.this)
                        .setTheme(R.style.FilePickerThemeRail)
                        .maxSelectable(1)
                        .forResult(FilePickerManager.REQUEST_CODE);
            }
        });
````
因为不懂kotlin 也是查询了一些资料才知道，建议增加下示例更方便大家使用，同时也感谢您的开源

**Comment by rosuH** [comment]
@qinyang1018 感谢建议😂。我已经添加了 Java 的使用示例。

7a82ca2185b9dc855f49dcc5ba51bee454ac17ae
