### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by popsa85** [rosuH/AndroidFilePicker#52]
How to translate "Select all" and "Done" buttons ?

**Comment by rosuH** [comment]
In 0.5.3, you can using [`setText`](https://github.com/rosuH/AndroidFilePicker/blob/d5e2f7867dc819347bdf6984308cbe1831d8b218/sample/src/main/java/me/rosuh/sample/SampleActivity.kt#L188) method to custom most text in UI.

```kotlin
FilePickerManager.from(this)
    .setText("A", "B", hadSelectedStrRes = R.string.demo_test_had_selected, confirmText = "C", emptyListTips = "E")
    .forResult(1001)
```
