### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by popsa85** [rosuH/AndroidFilePicker#53]
Unable to open folder and mark file using remote control.

**Comment by rosuH** [comment]
What is remote control? 🤔

**Comment by popsa85** [comment]
It IR remote control on Android Tv Boxes. KeyEvent class in Adnroid API. Enter key in the emulator triggers this event https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_DPAD_CENTER

> NoNonsense FilePicker

 has no problem with this. This is very important for me, since most of my users use TV Boxes

**Comment by rosuH** [comment]
Thank you for your explanation, because I did not involve in the development of TV, so I ignored the compatibility of this part. I have already started to develop this part of the function.  It may take some time.

**Comment by popsa85** [comment]
I look forward to new versions. Thanks for your work.
