### ISSUE TITLE
单选问题

### ISSUE THREAD

**Issue by hongyanfengzi** [rosuH/AndroidFilePicker#55]
.showCheckBox(false)   没有作用 , 能不能点击文件列表item, 直接回调, 而不是勾了复选框 , 再点击确认  , 在返回, 即FileItemOnClickListenerImpl 这个里面提供下单项点击的实现

**Comment by rosuH** [comment]
感谢反馈，单选这块的逻辑确实有待加强。
只是需求有千万，无法面面俱到。目前也在思考如何兼顾扩展性和可用性。
当下会做的：
1. 单选模式下使用单选框代替多选框
2. 优化对 item 回调的处理

**Comment by hongyanfengzi** [comment]
多谢关注啊, 这个优化完能否通知下, 不胜感激!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 中午11:53
收件人:&nbsp;"rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;;
抄送:&nbsp;"李辉"<1025208554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rosuH/AndroidFilePicker] 单选问题 (#55)




感谢反馈，单选这块的逻辑确实有待加强。
 只是需求有千万，无法面面俱到。目前也在思考如何兼顾扩展性和可用性。
 当下会做的：
  
单选模式下使用单选框代替多选框
 
优化对 item 回调的处理

**Comment by rosuH** [comment]
好的👌

**Comment by hongyanfengzi** [comment]
能否去掉,全选, 和已选择多少个的文字显示, 变成可配置的, 这个在小屏幕手机上, 会重叠显示, 也有不需要此功能的场景

**Comment by rosuH** [comment]
收到，感谢反馈

**Comment by hongyanfengzi** [comment]
大佬, 什么时候能修复下这个问题啊, 我都想导个moudle自己改了, 感谢提供这个方便使用的文件库啊!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 上午9:59
收件人:&nbsp;"rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;;
抄送:&nbsp;"李辉"<1025208554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rosuH/AndroidFilePicker] 单选问题 (#55)




收到，感谢反馈

**Comment by rosuH** [comment]
全选可以按钮你调用`enableSingleChoice()`就可以去掉了。
这几天会改一下，预计这周末吧。会把单选模式(`enableSingleChoice()`)加强一下。包括换成单选框之类的。

**Comment by rosuH** [comment]
如果你项目紧急的话，可以直接自己拉下来先改一下。后期换成这个库，应该也不会对你的业务逻辑改动很多的。

**Comment by hongyanfengzi** [comment]
这个单选逻辑, 我自定义了那个item点击事件了, &nbsp;还可以接受, 现在就是这个全选问题, &nbsp;需要的话话, 我会尝试的, 谢谢回复啊!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 上午10:12
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "李辉"<1025208554@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] 单选问题 (#55)




如果你项目紧急的话，可以直接自己拉下来先改一下。后期换成这个库，应该也不会对你的业务逻辑改动很多的。

**Comment by hongyanfengzi** [comment]
好的, 十分感谢啊!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 上午10:11
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "李辉"<1025208554@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] 单选问题 (#55)




全选可以按钮你调用enableSingleChoice()就可以去掉了。
 这几天会改一下，预计这周末吧。会把单选模式(enableSingleChoice())加强一下。包括换成单选框之类的。

**Comment by rosuH** [comment]
@hongyanfengzi 您好，单选模式已经正式发布。
您可以使用最新的 `0.6.0` 体验。该版本对部分 API 亦有小改动，如果遇到问题也可以直接在本 issue 提出或新建一个新 issue 。

感谢反馈～

**Comment by hongyanfengzi** [comment]
好的，收到，十分感谢啊！------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>
发送时间: 2019年12月4日(星期三) 晚上7:40
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com>;
抄送: "hongyanfengzi"<1025208554@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [rosuH/AndroidFilePicker] 单选问题 (#55)



@hongyanfengzi 您好，单选模式已经正式发布。
 您可以使用最新的 0.6.0 体验。该版本对部分 API 亦有小改动，如果遇到问题也可以直接在本 issue 提出或新建一个新 issue 。
 
感谢反馈～
 
&mdash;

**Comment by hongyanfengzi** [comment]
你好, 我看了现在的逻辑, 单选情况下, 即使通过自定义item点击事件,获取到文件内容, 但是还是要操作, 确认按钮, 才能关闭界面。能不能开放出一个关闭页面的方法,  方便操作。 谢谢啊!

**Comment by hongyanfengzi** [comment]
我理解的单选, 应该是在点击文件item的时候, 直接回调完成的方法, 关闭界面就可以了, 因为用户不想操作一下勾选, 再去点击确定, 列表中也就不需要显示那个勾选的RadioButton.
我做了一点修改:
1. FileListAdapter
   在FileListItemSingleChoiceHolder中 isDir加了else的判断
 ```
  if (isDir) {
                mIcon.setImageResource(R.drawable.ic_folder_file_picker)
                mRbItem.visibility = if (isSkipDir) View.GONE else View.VISIBLE
                return
            } else {
                // 是文件
                mRbItem.visibility = if (isSingleChoice) View.GONE else View.VISIBLE
            }
```
2.FilePickerActivity  在onItemClick加上了单选的判断
 ```
  R.id.item_list_file_picker -> {
                if (file.isDirectory) {
                    
                } else {
                    if (FilePickerManager.config.singleChoice) {
                        if (item is FileItemBeanImpl) {
                            item.setCheck(true)
                        }
                        saveDataAndFinish()
                        return
                    }
                    FilePickerManager.config.fileItemOnClickListener?.onItemClick(
                        adapter as FileListAdapter,
                        view,
                        position
                    )
                }
            }

private fun saveDataAndFinish() {
        val list = ArrayList<String>()
        val intent = Intent()
        for (data in listAdapter!!.dataList!!) {
            if (data.isChecked()) {
                list.add(data.filePath)
            }
        }
        if (list.isEmpty()) {
            this@FilePickerActivity.setResult(Activity.RESULT_CANCELED, intent)
            finish()
        }
        FilePickerManager.saveData(list)
        this@FilePickerActivity.setResult(Activity.RESULT_OK, intent)
        finish()
    }
```
以上的修改, 仅针对我个人的需求, 十分感谢作者提供这个很棒文件选择库, 并耐心的回答我的问题, 再次感谢., 最后希望能适配下Androidx !!!

**Comment by rosuH** [comment]
@hongyanfengzi 感谢反馈，我正在考虑如何把你说的转换成一个优雅的实现 💇‍♂

**Comment by rosuH** [comment]
@hongyanfengzi AndroidX 目前已经适配。但是单选这个还没考虑好怎么做。因为这里其实要处理文件夹的问题。

如果使用者需要单选文件夹，那么选择和进入这两个行为就会冲突。

所以暂时不会改动这块功能，如果需要点击直接返回，那么可以设置 item 监听器，然后从 view 拿到 context 并结束当前 Activity。或者像您这样直接拉下来自己改改～
