### ISSUE TITLE
AudioFileType ogg

### ISSUE THREAD

**Issue by loicteillard** [rosuH/AndroidFilePicker#59]
please add ogg to audio filter

AudioFileType :
return when (suffix){
            "aif", "iff", "m3u", "m4a", "mid", "mp3", "mpa", "wav", "wma",**"ogg"** -> {
                true
            }
            else -> {
                false
            }
        }

**Comment by rosuH** [comment]
Add on [0.6.1](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.1).

Thanks for your feedback.
