### ISSUE TITLE
recyclerview滑动优化建议

### ISSUE THREAD

**Issue by limuyang2** [rosuH/AndroidFilePicker#6]
快速滑动时，列表会掉帧严重。
不建议在recycleView的item中使用`android.support.constraint.ConstraintLayout`约束布局作为根布局，其重复测量会导致严重性能问题。
建议使用传统的布局控件，例如线性布局、帧布局等等

**Comment by rosuH** [comment]
@limuyang2 嗨，感谢提出建议。关于此，我有几点发现要和您探讨一下：

我的测试环境是：OnePlus 3T  A3010 `H2OS 5.0.3` Android 8.0.0
 
1. 我使用 Demo 测试了一下快速滑动的情况，下面的 GPU 的绘制曲线

![gpu_render](https://user-images.githubusercontent.com/15865017/50502235-9c979f80-0a98-11e9-81dd-44a95b89c8cd.jpg)

根据[官方文档](https://developer.android.com/studio/profile/inspect-gpu-rendering?hl=zh-cn)
绘测、测量和布局的竖条区域，在快速滑动时，均在水平轴之下，也就是 60帧。
极少情况会出现掉帧情况。

2. 关于 `ConstraintLayout` 性能问题

据 [Developers Blog 此篇文章](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html)所说，性能应该还是要优于传统布局的。

我大致搜查了网上的一些例子，猜测可能是和 Android 版本的兼容性问题。您方便说下运行设备的情况吗？

**Comment by limuyang2** [comment]
`ConstraintLayout `在页面布局情况下，能减少嵌套，性能优于传统布局。但是在item中，受限于Android版本、以及support库版本差异，性能很不稳定。
https://juejin.im/post/5baedbf05188255c596714ab
这篇文章里也有提及：

> 减少布局层级，可以考虑使用自定义 View 来减少层级，或者更合理地设置布局来减少层级，不推荐在 RecyclerView 中使用 ConstraintLayout，有很多开发者已经反映了使用它效果更差，相关链接有：Is ConstraintLayout that slow?、constraintlayout 1.1.1 not work well in listview。

我的多个项目实测情况下来，问题确实有点严重。
测试机我采用的是 一加X，骁龙801处理器。
item使用`ConstraintLayout`，在`氢os2.0`，`Android 6.0`下，问题非常严重。在 `AOSP Android7.0`下，问题有所改善。
1、`ConstraintLayout`下测试，卡顿非常严重了，几乎没法使用：
![](https://i.loli.net/2018/12/28/5c25e7ed4f94d.png)  
[这是视频连接](https://www.lanzous.com/i2pyv5c)

2、我改为双 线性布局 嵌套后的效果，非常流畅：
![](https://i.loli.net/2018/12/28/5c25ee1c6700a.png)
视频就不录制了

使用线性布局修改的布局（简单修改了下）：
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/item_list_file_picker"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="?attr/selectableItemBackground"
    android:clickable="true"
    android:focusable="true"
    android:foreground="?attr/selectableItemBackground"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_vertical"
        android:padding="12dp">

        <ImageView
            android:id="@+id/iv_icon_list_file_picker"
            android:layout_width="30dp"
            android:layout_height="30dp" />

        <me.rosuh.filepicker.utils.PercentTextView
            android:id="@+id/tv_list_file_picker"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginLeft="12dp"
            android:layout_marginRight="12dp"
            android:layout_weight="1"
            android:ellipsize="end"
            android:maxLines="1"
            android:scrollHorizontally="true"
            android:textColor="@color/shrine_text_color"
            android:textSize="40px"
            tools:text="SD 存储卡SD 存储卡SD" />

        <CheckBox
            android:id="@+id/cb_list_file_picker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:clickable="false"
            android:focusable="false" />
    </LinearLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:background="#EEEEEE"
        android:orientation="horizontal" />

</LinearLayout>
```

**Comment by rosuH** [comment]
@limuyang2 感谢回复。我会立刻修复。

**Comment by limuyang2** [comment]
补充，又经测试  测试机 华为p10 ，Android 8.0 上情况类似。

**Comment by rosuH** [comment]
@limuyang2 嗨，我已经在 42b517b47fa411df2d19bbb5c3c551e796923d67 中将根布局改为了`RelativeLayout`。我考虑过使用 `LinearLayout`，但是嵌套所带来的性能损耗可能大于`RelativeLayout`的测量损耗。

并不是十分可以量化的比较，所以如果您有疑问或建议可以立刻指出来。感谢您的帮助~

--- 
此`dev`如果您方便可以测试一下，其余的我会解决完 #7 后再 `release` 出来~

**Comment by limuyang2** [comment]
> @limuyang2 嗨，我已经在 [42b517b](https://github.com/rosuH/AndroidFilePicker/commit/42b517b47fa411df2d19bbb5c3c551e796923d67) 中将根布局改为了`RelativeLayout`。我考虑过使用 `LinearLayout`，但是嵌套所带来的性能损耗可能大于`RelativeLayout`的测量损耗。
> 
> 并不是十分可以量化的比较，所以如果您有疑问或建议可以立刻指出来。感谢您的帮助~
> 
> 此`dev`如果您方便可以测试一下，其余的我会解决完 #7 后再 `release` 出来~

ok，明天我再测试，RelativeLayout和LinearLayout的性能差距很难量化，这个影响应该不大。

**Comment by rosuH** [comment]
嗨，此 issue 将被关闭，如果上述问题仍未解决，您可以重开此 issue。
