### ISSUE TITLE
请问支持文件移动删除，文件夹移动删除吗

### ISSUE THREAD

**Issue by Mayo92** [rosuH/AndroidFilePicker#62]
有一个需求用我的应用打开特定的文件后保存到自己的文件夹中，文件夹里可以创建文件夹及移动文件等，谢谢

**Comment by rosuH** [comment]
这个库不支持对文件或文件夹进行写入操作，也就是在库里删除、移动和创建文件。
但是您可以通过这个库拿到用户所选择的文件的路径，然后后续自行编写代码实现。
不知道这样是否符合您的需求？

**Comment by Mayo92** [comment]
> 这个库不支持对文件或文件夹进行写入操作，也就是在库里删除、移动和创建文件。
> 但是您可以通过这个库拿到用户所选择的文件的路径，然后后续自行编写代码实现。
> 不知道这样是否符合您的需求？

好的谢谢
