### ISSUE TITLE
建议增加图片预览

### ISSUE THREAD

**Issue by Eaken** [rosuH/AndroidFilePicker#63]
因为是个文件选择器，要让用户选文件，从用户角度出发应该是要看到自己选的是个啥玩意，而不仅仅是文件名和选项左边的不知道是什么的图片，视频预览图也可以做，MediaMetadataRetriever和开源的FFmpegMediaMetadataRetriever都可以，预览图可以放在子线程慢慢加载，但我觉得必须得出来。以上是我的建议

**Comment by Eaken** [comment]
还有一个更方便的，我突然发现Glide也能加载视频预览图，但我没看出他源码怎么加载的，之前因为Glide老是会自己加个fragment影响我在fragment之间共享元素的使用，就没怎么调试Glide，今天自己做文件选择器的时候突然就发现了新大陆。

**Comment by rosuH** [comment]
图片预览已经在 [0.6.2](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.2) 中添加，感谢建议～
