### ISSUE TITLE
不支持Androidx吗？

### ISSUE THREAD

**Issue by EvanZch** [rosuH/AndroidFilePicker#64]
![image](https://user-images.githubusercontent.com/22145615/78549059-5650f480-7834-11ea-8831-5d3633bb3f42.png)

如图，运行不起来

**Comment by rosuH** [comment]
我刚刚创建了一个全新的 AndroidX 项目，可以直接使用。有什么报错信息吗？

**Comment by EvanZch** [comment]
在gradle.properties中加上图上两行也可以吗？我把项目直接拉下来添加后也跑不起来啊，当时比较急，没有深研究，后面换了其他的库，我晚点再看看

**Comment by EvanZch** [comment]
> 我刚刚创建了一个全新的 AndroidX 项目，可以直接使用。有什么报错信息吗？

不好意思啊，我刚刚新建一个项目试了一下，确实没问题，前面可能是我项目冲突了，我抽空看看问题。
