### ISSUE TITLE
[AndroidX support requested]错误 Unable to start activity 

### ISSUE THREAD

**Issue by huhao1987** [rosuH/AndroidFilePicker#67]
java.lang.RuntimeException: Unable to start activity ComponentInfo{hh.rpgmakerplayer/me.rosuh.filepicker.FilePickerActivity}: android.view.InflateException: Binary XML file line #76 in 
xx:layout/main_activity_for_file_picker: Binary XML file line #76 in 
xx:layout/main_activity_for_file_picker: Error inflating class androidx.swiperefreshlayout.widget.SwipeRefreshLayout

需要自己导入Androidx的SwipeRefreshLayout库

**Comment by huhao1987** [comment]
建议出个支持Androidx的版本,毕竟还是有人会使用Andoridx.

**Comment by rosuH** [comment]
请问您的项目是 AndroidX 吗？

**Comment by huhao1987** [comment]
是的,我的项目是用的Androidx

**Comment by huhao1987** [comment]
是新建的项目,properties下也开启了,默认打开的.但是导入直接报错,添加Androidx版本的SwipeRefreshLayout之后就正常了

**Comment by rosuH** [comment]
可以把您新建的项目打包传上来看看嘛？（File --> Export to Zip File）

**Comment by huhao1987** [comment]
奇怪了,又新建了一个新项目正常了

**Comment by rosuH** [comment]
我会在近期加上 AndroidX 的版本，感谢反馈～

**Comment by rosuH** [comment]
AndroidX 版本已经更新：
```
dependencies {
    implementation 'me.rosuh:AndroidFilePicker:0.6.2-x'
}
```

有问题欢迎随时沟通，感谢反馈。
