### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by Jetlonglong** [rosuH/AndroidFilePicker#68]
作者您好 请问为什么已经赋予了权限还是报这个错误
![image](https://user-images.githubusercontent.com/51015752/80272947-abc84500-8700-11ea-8c75-4046820d5e84.png)

**Comment by rosuH** [comment]
请问您的 log 是翻译过的吗？可以把原信息发一下。以及一些基础的信息：

1. AndroidX 还是 support
2. targetAPI 多高
3. 设备 API 多少

是不是 targetAPI >= 29  跑在 Android 10+ 设备上呢？
因为此库目前还正式兼容 Android 10+ 的存储变更，需要在 `AndroidManifest.xml` 中开启 `android:requestLegacyExternalStorage`。

参见：https://github.com/rosuH/AndroidFilePicker/issues/46#issuecomment-562480118

**Comment by Jetlonglong** [comment]
> 请问您的 log 是翻译过的吗？可以把原信息发一下。以及一些基础的信息：
> 
> 1. AndroidX 还是 support
> 2. targetAPI 多高
> 3. 设备 API 多少
> 
> 是不是 targetAPI >= 29 跑在 Android 10+ 设备上呢？
> 因为此库目前还正式兼容 Android 10+ 的存储变更，需要在 `AndroidManifest.xml` 中开启 `android:requestLegacyExternalStorage`。
> 
> 参见：[#46 (comment)](https://github.com/rosuH/AndroidFilePicker/issues/46#issuecomment-562480118)

嗯嗯 是Android10+的设备  模拟器运行都是正常的 
好的 谢谢作者

**Comment by rosuH** [comment]
您好，请问现在情况排查得如何了？

**Comment by Jetlonglong** [comment]
> 您好，请问现在情况排查得如何了？
加上 android:requestLegacyExternalStorage  这个就解决啦 
谢谢作者
