### ISSUE TITLE
文件扫描性能优化建议

### ISSUE THREAD

**Issue by limuyang2** [rosuH/AndroidFilePicker#7]
1、使用了kotlin，为何还要使用`findViewById`。是有什么特殊的原因么？

2、进入activity后，扫描文件的工作应该放到`子线程` 或 `协程`中去做，就不出现莫名其妙的启动等待时间。（个人建议放入协程，第一轻量级，第二异地可以当同步，不影响现有逻辑顺序）

**Comment by rosuH** [comment]
@limuyang2 嗨，在最新的 release 版本中，我已经尝试使用协程将文件 I/O 从 UI 线程分离。

但是，在大量文件（当文件数量达到 50000 个时，遍历时间为 6s ）的情况下，对`item`操作的性能依旧比较低。这是因为选择前会遍历列表获取可选项的数量。

这是一个已知问题，我将会在接下来的时间着手优化这方面的代码架构。
感谢您的建议~
