### ISSUE TITLE
关于遍历文件的问题

### ISSUE THREAD

**Issue by xiaohuazai** [rosuH/AndroidFilePicker#70]
现在是只能扫描一层的文件么？比如说：想扫描本地的所有doc文件，这种扫描逻辑是要自己去实现的么？

**Comment by rosuH** [comment]
是的。如果说要获取某种类型的文件的话，目前请您尝试官方的：
1. [访问媒体文件](https://developer.android.google.cn/training/data-storage/files/media#access-files)
2. [打开文档](https://developer.android.google.cn/guide/topics/providers/document-provider#client)

等相关接口。
