### ISSUE TITLE
导航栏和状态栏重叠,建议适配一下

### ISSUE THREAD

**Issue by yzc90912** [rosuH/AndroidFilePicker#71]
导航栏和状态栏重叠,建议适配一下

**Comment by rosuH** [comment]
请问能附上截图吗？我这里貌似没有问题

**Comment by LeooooL** [comment]
![1592463997(1)](https://user-images.githubusercontent.com/11988385/84988926-69a60780-b175-11ea-8500-749440e0644a.jpg)

我这里复现的场景是使用了侧滑返回Activity的框架 [SmartSwipe](https://github.com/luckybilly/SmartSwipe")，可以对FilePickerActivity屏蔽侧滑返回功能

**Comment by rosuH** [comment]
收到，我晚上验证下。

**Comment by rosuH** [comment]
@LeooooL @yzc90912 
大家好，已经在 0.6.3 版本中修复此问题，感谢反馈。
