### ISSUE TITLE
文件是否能根据时间倒序?

### ISSUE THREAD

**Issue by 18833013313** [rosuH/AndroidFilePicker#72]
文件是否能根据时间倒序?还有能有在选择文件页面()FilePickerActivity)加一个切换路径的选项

**Comment by rosuH** [comment]
@18833013313 根据时间排序是可以做到的。因为过滤器会给你路径列表。
用路径可以拿到 `File` 对象，进而拿到该文件的最新改动时间。自己做好排序返回进去即可。

- 通过路径获得改动时间：https://stackoverflow.com/a/2390177/7293728
- [自定义过滤器](https://github.com/rosuH/AndroidFilePicker/wiki/2.-%E8%BF%87%E6%BB%A4%E5%99%A8%EF%BC%9A%E5%8F%AA%E6%98%BE%E7%A4%BA%E6%9F%90%E7%A7%8D%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%96%87%E4%BB%B6)

动态切换路径暂时还不支持，后续会考虑。
