### ISSUE TITLE
用java 过滤只显示指定的后缀 怎么用

### ISSUE THREAD

**Issue by yuxue521** [rosuH/AndroidFilePicker#77]
`.filter(object : AbstractFileFilter() {
                    override fun doFilter(listData: ArrayList<FileItemBeanImpl>): ArrayList<FileItemBeanImpl> {
                        // 2. 接收结果列表，然后过滤出您想要的类型
                        // 2. Receive result list and filter what you want
                        listData.removeAll {
                            (it.fileType !is CustomFileType) && !it.isDir
                        }
                        return listData
                    }
                })`
`    class CustomFileType(
        override val fileType: String = "",
        override val fileIconResId: Int = R.drawable.ic_unknown_file_picker
    )      : FileType {
        override fun verify(fileName: String): Boolean {
            return fileName.endsWith("123")
        }
    }`

我是java 初学者  对Kotlin 这高大上的东西更难理解  像上面的 这个Kotlin demo 怎么用 java 方式写出来
感谢

**Comment by rosuH** [comment]
@yuxue521 
详细说明在此：https://github.com/rosuH/AndroidFilePicker/wiki/5.-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B-Custom-your-file-type 。

您仍需实现您自己的 `AbstractFileDetector` 类。然后才到第三步中使用。

如果您项目使用的是 JDK8+ 的话，实际上也可以用 Stream API 来操作列表（也就是示例中的 `list.removeAll`）。

而如果是 JDK8 以下的版本，就是自己新建一个列表对象，然后遍历 `listData` 拿到您所需要的 item 加到您自己的列表中。
最后返回您的列表即可。库将根据您返回的列表来渲染 UI。

可以参看 [这个 issues](https://github.com/rosuH/AndroidFilePicker/issues/73#issuecomment-645701611)。不过他用的是之前的 API，名字和最新版的有所差别。

`AbstractFileType` --> `AbstractFileDetector`
`AbstractFileType` -->  `AbstractFileDetector`
`FilePickerConfig#fileType()` --> ` FilePickerConfig#customDetector`

**Comment by rosuH** [comment]
因为您的需求比较简单，您也可以直接用 `filter` 来实现：
 
```java
FilePickerManager.INSTANCE
    .from(this)
    .filter(new AbstractFileFilter() {
        @NotNull
        @Override
        public ArrayList<FileItemBeanImpl> doFilter(@NotNull ArrayList<FileItemBeanImpl> listData) {
            ArrayList<FileItemBeanImpl> myList = new ArrayList<>(listData.size());
            for (FileItemBeanImpl itemBean : listData) {
                if (itemBean.getFileName().endsWith("mp3")){
                    myList.add(itemBean);
                }
            }
            return myList;
        }
    })
    .forResult(101);
```

**Comment by yuxue521** [comment]
太感谢了
