### ISSUE TITLE
建议：能否提供这种页面风格

### ISSUE THREAD

**Issue by zaaach** [rosuH/AndroidFilePicker#79]
![68747470733a2f2f696d6167652e6962622e636f2f6d37357552462f6465766963655f323031375f30335f31305f3136333930302e706e67](https://user-images.githubusercontent.com/9695127/86505925-dae3ec80-bdfc-11ea-9cbf-96981db6d697.png)
感觉这种选择文件方式会比较方便些~

**Comment by rosuH** [comment]
这种需要查找所有文件类型，暂时应该不会支持。您可以直接使用 https://github.com/DroidNinja/Android-FilePicker。

感谢反馈~
