### ISSUE TITLE
指定选择数量后 与顶部toolbar中的全选功能冲突

### ISSUE THREAD

**Issue by prczhb** [rosuH/AndroidFilePicker#8]
1.指定数量功能失效:
当指定选择数量后,点击全选功能,仍然可以选中全部(超出指定数量),并且过滤掉的文件貌似也被选中,但是不会将数据返回至activity中.
2.能选中过滤掉的文件
当指定选择数量后,在文件过滤后,点击全选,估计是选中了过滤掉的文件,只是没显示,然后点击确认 会提示选择超过多个,界面上看起来并没有选这么多,可能选中的那些是过滤掉的文件,

**Comment by rosuH** [comment]
@prczhb 您好，请问您是使用 Demo 出错了吗？我刚尝试了并没有复现。

或者您贴上您的代码看看？

**Comment by prczhb** [comment]
@rosuH 打扰了 这好像是我这里代码的问题.....
不过还存在这么一个问题:
我过滤一下我要选择的文件类型 ,设置一下要选择的文件数量,
然后跳转到框架里的文件管理器界面 ,
进去他有一个默认的目录 ,就是文件夹根目录吧(SD存储卡),
因为我过滤了文件类型,在根目录中没有我存在的文件,
然后我点击全选操作,此时不点击确定返回,而是再点击文件列表的其他的一个子文件夹 (比如SD存储卡 里的 007文件夹,既"sd/007/"这个目录),
这个子文件夹里有我想要的文件,可是当我点击选中它时,提示"最多只能选择*项",可是事实是我一项都没选中过

上述问题是我项目中的,我又试了试demo 也是这样,
demo中 点击"单选文件" -- 跳转到文件选择器 -- 此时不选择文件,而是找到一个为空的文件夹点进去,--点击 全选 --然后 再找到一个有文件的文件目录里 ,选中文件 -- 会发现一个文件都没选中, -- 手动选中文件 -- 会提示 "最多只能选择一项" 但实际上目前为止一项文件都没选中,点击确认返回,提示"没有选择图片"

(一直上传图片失败...bao抱歉没图片说明)

然后toast 的那个提示文字没有居中是什么鬼,,,,,,目前看来是顶部居中对齐,没有上下居中对齐

**Comment by prczhb** [comment]
我最开始描述的问题,就是刚刚描述的那个bug影响的,加上我自己代码问题,把我整蒙了

**Comment by rosuH** [comment]
@prczhb 收到！我待会复现一下。

**Comment by rosuH** [comment]
@prczhb 嗨，问题已经在 https://github.com/rosuH/AndroidFilePicker/commit/0d697fbf893c2d317caa481cbaa527e85838c875 中解决啦。您可以尝试 `0.4.2` 版本，看看是否还有问题。

感谢您提供的建议 🌹

**Comment by prczhb** [comment]
嗯 没有问题了 谢谢您的帮助
