### ISSUE TITLE
Image files on android 11 are treated as folders (screenshots)

### ISSUE THREAD

**Issue by s2010** [rosuH/AndroidFilePicker#80]
Thank you for the exceptional work here, literally the only thing that worked for me.

On android 11 the lib treats images as empty folders, please check the screenshots.

![image2](https://user-images.githubusercontent.com/12055670/86846097-19a2cc80-c0b3-11ea-8efb-e4ba2c1aa516.png)

![image1](https://user-images.githubusercontent.com/12055670/86846100-1ad3f980-c0b3-11ea-84f1-1d3bed5763ac.png)

How do you think we can solve this, thanks again.

**Comment by rosuH** [comment]
@s2010 There is some information I need:

1.  Does your project have the [requestLegacyExternalStorage](https://developer.android.com/reference/android/R.attr#requestLegacyExternalStorage) feature enabled? If you don't, pls enable it. This lib is not supporting the new legacy storage feature which add-in Android 10+. 

2. This lib using file extension (etc. `.jpg`) to detected file mime type. It is not very accurate. So check your actual file name via other file browser or file manager APP. If filename is correct, try to log them out:

```Kotlin
FilePickerManager
    .from(this@SampleActivity)
    .setTheme(getRandomTheme())
    .filter(object : AbstractFileFilter() {
        override fun doFilter(listData: ArrayList<FileItemBeanImpl>): ArrayList<FileItemBeanImpl> {
            listData.forEach {
               // The correct result, all would be absolute path.
                Log.i("SampleActivity", "${it.filePath}/${it.fileName}")
            }
            return listData
        }
    })
    .forResult(FilePickerManager.REQUEST_CODE)
```

Thanks for your feedback. Looking forward to your new info.
