### ISSUE TITLE
请问作者还打算适配Android 11吗？

### ISSUE THREAD

**Issue by FFirX** [rosuH/AndroidFilePicker#81]
首先感谢作者提供了这个美观好用的库。
根据Google官方的更新文档说明，目标平台为Android 11时，requestLegacyExternalStorage将被忽略。
[https://developer.android.com/preview/privacy/storage?hl=zh-cn#scoped-storage](url)
明年上传到商店的App将强制使用API Level 29，届时这个库将不能正常运行（表现是一直等待转圈）。根据作者在这个issue的回复，在2019年时并没有打算做兼容。  #46 
现在已经过去好几个月了，官方已经说明会强制使用，那么请问作者，现在是否有做兼容的计划？
兼容方案，比如说，只能打开应用专有目录？

**Comment by rosuH** [comment]
@FFirX 您好，抱歉这么晚回复您。这个库的后期计划正在规划中，Android 分区存储的兼容工作也正**尝试**进行。

有进度将随时周知您，感谢反馈。

**Comment by rosuH** [comment]
@FFirX 
您好，考虑再三，目前决定暂不对 Android 11 做兼容。私有目录的应用场景可能还是太小了。

如果有比较明确的业务场景，那么开发起来也会更精确一点。如果您有其他任何需求或想法，也欢迎您随时反馈。

感谢～
