### ISSUE TITLE
很不错的框架，提个建议

### ISSUE THREAD

**Issue by keaitao0321** [rosuH/AndroidFilePicker#82]
文件过滤只针对一级目录有效，如果是能读取手机中的所有类型文件就好了
建议参照 
Android-FilePicker 
对项目进行优化，开发更多功能

**Comment by rosuH** [comment]
如果要获取所有类型的话，实现原理和现在就差别很大了。如果自己实现全盘遍历，是比较重的操作。

到了 Android 11 之后，存储权限收窄，如果用系统 API 也只能拿到媒体类型文件，拿不到文档或其他自定义文件。即便是您提到的 Android-FilePicker 也没有好的解决方法。所以获取全部文件类型的这个功能，我也是想了再想，没用真正动手。

无论如何，感谢反馈～
