### ISSUE TITLE
选择文件 在文件列表未出来之前点击确认按钮 

### ISSUE THREAD

**Issue by LGT1995** [rosuH/AndroidFilePicker#84]
选择文件 在文件列表为出来之前 点击确定按钮 崩溃
at me.rosuh.filepicker.FilePickerActivity.onClick(FilePickerActivity.kt:547)
![image](https://user-images.githubusercontent.com/31907875/88624275-4017be80-d0d9-11ea-8faa-483f59d6308f.png)

**Comment by rosuH** [comment]
你好，已经在 0.6.5 版本修复。

感谢反馈～
