### ISSUE TITLE
文件类型过滤

### ISSUE THREAD

**Issue by cybkw** [rosuH/AndroidFilePicker#87]
请问大佬，我需要返回 一系列文件类型，如txt , doc ,pdf等， 每种类型都需要自定义一个吗？继承FileType类？

**Comment by rosuH** [comment]
有两种方式可以实现。看你的个人选择。
- 每种文件都定义一个文件类型，也就是实现 `FileType` 类，然后再实现自己的文件检测器，也即是实现 `AbstractFileDetector` 类。[自定义文件类型 Custom your file type](https://github.com/rosuH/AndroidFilePicker/wiki/5.-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B-Custom-your-file-type)
- 什么类型都不自定义，然后添加一个文件过滤器 `AbstractFileFilter` ，在 `filter` 中拿到列表，过滤后返回。[文件过滤器](https://github.com/rosuH/AndroidFilePicker/wiki/2.-%E8%BF%87%E6%BB%A4%E5%99%A8%EF%BC%9A%E5%8F%AA%E6%98%BE%E7%A4%BA%E6%9F%90%E7%A7%8D%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%96%87%E4%BB%B6)

## 为什么有两种实现？
如果你判断文件类型的方法比较复杂，那么推荐第一种，它就是为此而存在的。
- 这种方式会把判断文件的实现封装在 `FileType.verify()` 函数中
- 接着利用你自定义的「文件检测器」（AbstractFileDetector），调用 `verify` 方法，判断类型后填充到 `item` 的 `fileType` 中
- 最后在 `fileter` 里，直接使用 `item.fileType` 属性进行判断。

这种设计的初衷，就是让用户封装好各个类的判断方式到 `FileType` 里面，而隐藏实现细节，不会暴露到业务里去。

如果你的判断方法很简单，只是通过文件名后缀判断，或者你的类型很少，那么使用第二种相对直观一点。

第二种的问题就是要把判断类型的代码写在 `filter` 里面，不是很雅观就是了。

**Comment by cybkw** [comment]
感谢大佬，已经解决了。 库很优秀，如果能开放申请权限的结果回调结果就更好了

**Comment by rosuH** [comment]
@cybkw 好的，我会考虑。感谢反馈~

**Comment by rosuH** [comment]
新版本 0.6.6 简化了自定义文件类型的使用。参考 [wiki](https://github.com/rosuH/AndroidFilePicker/wiki/5.-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E4%BB%B6%E7%B1%BB%E5%9E%8B-Custom-your-file-type)。推荐使用这种方式自定义文件类型。
