### ISSUE TITLE
xml加载出现问题。

### ISSUE THREAD

**Issue by shenyutian** [rosuH/AndroidFilePicker#88]
me.rosuh.filepicker.FilePickerActivity}: android.view.InflateException: Binary XML file line #76: Binary XML file line #76: Error inflating class androidx.swiperefreshlayout.widget.SwipeRefreshLayout

**Comment by rosuH** [comment]
@shenyutian 你的项目是 AndroidX 的吗？那你要用 AndroidX 的版本哦

**Comment by shenyutian** [comment]
// 文件选择 https://github.com/rosuH/AndroidFilePicker/blob/master/README_CN.md
implementation 'me.rosuh:AndroidFilePicker:0.6.5-x'我也有点迷糊。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rosuH"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 中午12:06
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "自由之翼永恒"<358288839@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] xml加载出现问题。 (#88)





 
@shenyutian 你的项目是 AndroidX 的吗？那你要用 AndroidX 的版本哦

**Comment by rosuH** [comment]
@shenyutian 我自己新建的一个项目，是可以正常使用的。或者你手动把 [swiperefreshlayout](https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout) 依赖加进去。

**Comment by shenyutian** [comment]
好的，谢谢了。我新建了一个项目使用的确没问题。但是原本的项目在导入swiperefreshlayout&nbsp;依赖后也没问题了。这是什么原因呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rosuH"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 下午4:47
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "自由之翼永恒"<358288839@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] xml加载出现问题。 (#88)





 
@shenyutian 我自己新建的一个项目，是可以正常使用的。或者你手动把 swiperefreshlayout 依赖加进去。

**Comment by rosuH** [comment]
@shenyutian 我也不太清楚具体原因，可能是和库的打包有关系。你看看新项目有什么依赖是你老项目没有的。或者版本差异？

**Comment by shenyutian** [comment]
我一开始也怀疑是有什么不同的，但是，老项目也才昨天创建的，gradle版本也是一样的，差异性不大。脑壳痛。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rosuH"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 下午5:46
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "自由之翼永恒"<358288839@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] xml加载出现问题。 (#88)





 
@shenyutian 我也不太清楚具体原因，可能是和库的打包有关系。你看看新项目有什么依赖是你老项目没有的。或者版本差异？

**Comment by rosuH** [comment]
试试新版本 0.6.6-x。估计是库里没有加依赖的问题。 @shenyutian

**Comment by shenyutian** [comment]
好的，我试了一下。的确没问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rosuH"<notifications@github.com&gt;; 
发送时间: 2020年9月17日(星期四) 下午4:47
收件人: "rosuH/AndroidFilePicker"<AndroidFilePicker@noreply.github.com&gt;; 
抄送: "自由之翼永恒"<358288839@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [rosuH/AndroidFilePicker] xml加载出现问题。 (#88)





 
试试新版本 0.6.6-x。估计是库里没有加依赖的问题。 @shenyutian
