### ISSUE TITLE
Crash on Android 10.0

### ISSUE THREAD

**Issue by saleemchudhary** [rosuH/AndroidFilePicker#90]
Issue resolved

**Comment by saleemchudhary** [comment]
implementation 'me.rosuh:AndroidFilePicker:$latest_version'
what is the current version as i am using 

implementation 'me.rosuh:AndroidFilePicker:0.5.2'
may be its an older version

**Comment by saleemchudhary** [comment]
Resolved

**Comment by fukemy** [comment]
hi, how did u solved this?
