### ISSUE TITLE
如何实现文件大小过滤

### ISSUE THREAD

**Issue by Petterpx** [rosuH/AndroidFilePicker#91]
比如，只显示100M以下文件，或者选中文件时，我可以拿到一个监听事件提醒用户选择的文件大于指定限制。

**Comment by rosuH** [comment]
使用[过滤器](https://github.com/rosuH/AndroidFilePicker/wiki/2.-%E8%BF%87%E6%BB%A4%E5%99%A8%EF%BC%9A%E5%8F%AA%E6%98%BE%E7%A4%BA%E6%9F%90%E7%A7%8D%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%96%87%E4%BB%B6#%E4%B8%80%E4%B8%AA%E8%BF%87%E6%BB%A4%E5%99%A8)即可。

实现时，通过文件路径拿到 `File` ，据此得到文件大小。

**Comment by Petterpx** [comment]
感谢
