### ISSUE TITLE
android 11 正式版发布了~考虑支持下不

### ISSUE THREAD

**Issue by badboy-tian** [rosuH/AndroidFilePicker#92]
RT

**Comment by rosuH** [comment]
请问您在 Android 11 的需求场景是什么呢？因为当初考虑到 Android 11 对存储的收紧，以及提供了一些文件的获取方式，所以觉得不是很有必要（也做不到）兼容 Android 11。

因为存储权限收窄，所以库无法获取外部存储目录，这样这个库就变得很鸡肋了。

**Comment by badboy-tian** [comment]
就是从sdcard中选择音频, 视频呀

rosuH <notifications@github.com> 于2020年9月24日周四 下午3:07写道：

**Comment by rosuH** [comment]
哦哦了解。目前 `MediaStore` 在开启了分区存储后，将只显示图片、视频和音频。如果要使用新 API 查询文件的话，改动会比较大。所以不会那么完成这部分工作。

**Comment by rosuH** [comment]
@badboy-tian 已经支持 Android 11。请使用 [0.7.4](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.7.4) 版本。

**Comment by badboy-tian** [comment]
![image](https://user-images.githubusercontent.com/2835129/133023613-3e732a75-ae79-4962-8c3a-991c3b6db133.png)
jitpack是不是有问题 一直生成不了

**Comment by rosuH** [comment]
@badboy-tian Jitpack 服务挂了。还没有恢复呢...

![image](https://user-images.githubusercontent.com/15865017/133023743-265cef23-08ad-4556-841f-9fa8723a9a2d.png)


https://status.jitpack.io/
