### ISSUE TITLE
过滤器内存泄漏

### ISSUE THREAD

**Issue by jusyps** [rosuH/AndroidFilePicker#93]
列表中能否显示文件大小，需要如何设置

**Comment by rosuH** [comment]
暂时不支持对列表 UI 的自定义哦。可以实现对数据的过滤和修改。

**Comment by jusyps** [comment]
![1607761518(1)](https://user-images.githubusercontent.com/21016535/101979570-0b2b9300-3c99-11eb-96d8-83dac0f208a5.jpg)在添加过滤器之后，会出现这个内存泄漏的问题。不加过滤器的话是好的

**Comment by jusyps** [comment]
我是用Java写的
