### ISSUE TITLE
选择文件夹时如何选择存储的根目录

### ISSUE THREAD

**Issue by DMingOu** [rosuH/AndroidFilePicker#94]
在做文件保存到指定文件夹时，过滤掉了非文件夹，貌似无法直接回调判断用户是否选择存储的根目录？

在未选择的情况下点击确定与直接按返回键，都会有：
- FilePickerManager.REQUEST_CODE 都是 Activity.RESULT_CANCELED，
- FilePickerManager.obtainData() 都是空数组

望解答

**Comment by rosuH** [comment]
这个时候要把文件夹作为选择项供用户选择。

```
FilePickerManager
    .from(this@SampleActivity)
    .skipDirWhenSelect(false)
    .forResult(FilePickerManager.REQUEST_CODE)
```

参考 Sample 里的「[单选文件夹](https://github.com/rosuH/AndroidFilePicker/blob/76871932cd0634499906474c8fe9f24626a2d6e1/sample/src/main/java/me/rosuh/sample/SampleActivity.kt#L119)」示例：

https://github.com/rosuH/AndroidFilePicker/blob/76871932cd0634499906474c8fe9f24626a2d6e1/sample/src/main/java/me/rosuh/sample/SampleActivity.kt#L119-L133

**Comment by DMingOu** [comment]
>     private fun jumpToSelectTargetDir(){
>         val pickerConfig = FilePickerManager
>             .from(this)
>             .maxSelectable(1)     //只可选择单项
>             .filter(excludeFileFilter) //只显示文件夹
>             .skipDirWhenSelect(false)
>             .setTheme(R.style.FilePickerThemeReply)
>         pickerConfig.forResult(FilePickerManager.REQUEST_CODE)
>     }
我使用了以上的配置，目前已经可以实现回调单个文件夹的路径，但是貌似无法判断回调用户是否就是选择了根存储目录作为目标文件夹？

**Comment by rosuH** [comment]
你说得对，这里确实漏考虑了根目录的问题。

简单的改法：或许可以点返回键设为 cancel，点确定键则为 ok。然后我会把根目录返回给调用者。

优雅的改法，就是把根目录也作为选择项。

我这两天会改一下这个问题。如果你不急的话可以等新版本。如果急的话，可以自己 fork 改一下。

感谢反馈~

**Comment by rosuH** [comment]
我提交一个修复，你可以先试试那个版本能否满足你的需求：

需要设置 `skipDirWhenSelect(false)` 进入文件夹可选模式，才会显示根目录出来。

```
implementation 'me.rosuh:AndroidFilePicker:dev-b69801755e-1'
```

如果没问题，我就合并到正式版中。

**Comment by DMingOu** [comment]
@rosuH 

> implementation 'me.rosuh:AndroidFilePicker:dev-SNAPSHOT'

恩，可以回调选择到根目录了，谢谢~
大概什么时候会发布新版本 : )

**Comment by rosuH** [comment]
@DMingOu 明天~

**Comment by DMingOu** [comment]
好的，Thanks :)

**Comment by rosuH** [comment]
你好，新版本 [0.6.7](https://github.com/rosuH/AndroidFilePicker/releases) 已经发布，你可以随时更新尝试。有问题随时沟通。

感谢反馈~
