### ISSUE TITLE
main_activity_for_file_picker.xml这个布局的确认按钮文字显示不全

### ISSUE THREAD

**Issue by Mr-jinPH** [rosuH/AndroidFilePicker#95]
main_activity_for_file_picker.xml这个布局的确认按钮文字显示不全

**Comment by rosuH** [comment]
@Mr-jinPH 麻烦提供下运行设备信息以及项目相关信息：OS Version, compileVersoin, targetVersion。

以及，是不是所有设备都可以复现？我自己两台手机无法复现。

**Comment by Mr-jinPH** [comment]
你好,我的APP主题使用了 material后出现这种情况的, 换成AppCompat就没问题了.使用了3台测试机,2台华为一台华硕都复现了.

**Comment by rosuH** [comment]
嗯嗯，已经确认问题。晚上看看如何处理

**Comment by rosuH** [comment]
你好，请尝试 [0.6.8](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.8) 版本。如果你的项目是 AndroidX，推荐使用 [0.6.8-x](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.8-x)。

有问题欢迎随时反馈，谢谢～

**Comment by Mr-jinPH** [comment]
> 你好，请尝试 [0.6.8](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.8) 版本。如果你的项目是 AndroidX，推荐使用 [0.6.8-x](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.8-x)。
> 
> 有问题欢迎随时反馈，谢谢～

好的 .谢谢
